#!/usr/bin/env python3
"""
Swept-Level FVGC Break-&-Retest — §4 causal per-signal feature enrichment.

EVERY feature here is computed strictly AS-OF the signal's entry bar. No
full-session lookahead. Each compute function's docstring states the exact
information window it reads ("as-of" availability) — this is the artifact the
lookahead checkpoint audits before any mining runs.

Inputs (all already cached, no signal regeneration):
  - logs/baseline_trades.csv         : 6,614 FVGC signals, 8yr, with entry_idx,
                                       fvg zone, sl_dist, MFE/MAE, hit_XR.
  - data/consolidated/...30s.csv     : canonical 30s bars (entry_idx indexes this).
  - data/levels/liquidity_levels.csv : per-date level universe (session + HTF FVG).
  - data/levels/daily_volume_profile : daily POC/VAH/VAL/va_width (for lag-1 + dev).
  - data/trading_days/trading_days.csv: regime layer (prior_day_type, gap, vixy...).

Mechanism discipline (§6):
  - STOP-LIQUIDITY levels (session H/L, swings, HTF-FVG, OR, round numbers) are
    eligible as SWEEP FUEL (§4.1).
  - MEAN-REVERSION magnets (VWAP, POC) are eligible as TARGET/location (§4.3/§4.4)
    but NOT as sweep provenance.

Output: results/signals_enriched.csv (one row per baseline signal + features).
"""

from __future__ import annotations

import argparse
import sys
import time as _time
from datetime import time as dtime
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from fvgc.data import load_candles  # noqa: E402
from fvgc.volume_profile import compute_volume_profile  # noqa: E402
from shared.vwap import session_vwap  # noqa: E402
from data.levels.enrich_trades_with_levels import filter_trade_date_levels  # noqa: E402

# ===================================================================
# Paths / constants
# ===================================================================

CONS_30S = ROOT / 'data' / 'consolidated' / 'nq-front-month.ohlcv-30s.csv'
# Frozen study-owned signal snapshot. The shared logs/baseline_trades.csv is
# periodically REGENERATED by a background data-update job against a rolling
# (shorter) candle set, which breaks entry_idx alignment with the full 8yr
# consolidated file. We pin to a frozen 8yr copy (verified 0/6614 misaligned)
# so the study stays reproducible regardless of background rewrites.
_FROZEN = Path(__file__).resolve().parent / 'baseline_signals_8yr.frozen.csv'
BASELINE = _FROZEN if _FROZEN.exists() else ROOT / 'logs' / 'baseline_trades.csv'
LIQUIDITY = ROOT / 'data' / 'levels' / 'liquidity_levels.csv'
DAILY_VP = ROOT / 'data' / 'levels' / 'daily_volume_profile.csv'
TRADING_DAYS = ROOT / 'data' / 'trading_days' / 'trading_days.csv'

STUDY_DIR = Path(__file__).resolve().parent
RESULTS_DIR = STUDY_DIR / 'results'

RTH_OPEN = dtime(9, 30)

# "FVG sits at a level" tolerance pad (NQ pts) — level must lie within the FVG
# zone expanded by max(LEVEL_PAD, 0.5*fvg_size). Flexible default per Phil;
# still swept as a parameter in Phase B ({5,10,20,30}).
LEVEL_PAD = 20.0

# Level groups that are STOP-LIQUIDITY pools (sweep-eligible, §6).
STOP_LIQUIDITY_GROUPS = frozenset({
    'prev_day', 'london', 'asia', 'overnight', '6am', 'nwog',
    'bsl_ssl', 'opening_range',
    'htf_fvg_15m', 'htf_fvg_1H', 'htf_fvg_4H', 'htf_fvg_Daily',
})
HTF_GROUPS = ('htf_fvg_15m', 'htf_fvg_1H', 'htf_fvg_4H', 'htf_fvg_Daily')

# Round-number magnet grid (NQ): 50 and 100 pt levels.
ROUND_50 = 50.0
ROUND_100 = 100.0


# ===================================================================
# Precompute: candle arrays + per-date indexing
# ===================================================================

class CandleIndex:
    """Holds candle arrays + per-date RTH-open index for fast as-of slicing."""

    def __init__(self, candles: pd.DataFrame):
        self.high = candles['high'].to_numpy(dtype=float)
        self.low = candles['low'].to_numpy(dtype=float)
        self.close = candles['close'].to_numpy(dtype=float)
        self.open = candles['open'].to_numpy(dtype=float)
        self.vol = candles['volume'].to_numpy(dtype=float)
        ts_ny = candles['timestamp_ny']
        self.date = ts_ny.dt.date.to_numpy()
        self.tod = ts_ny.dt.time.to_numpy()
        # utc ns for exact created_at -> idx lookup
        self.ts_utc_ns = candles['timestamp_utc'].astype('int64').to_numpy()
        self.ts_ny = ts_ny.to_numpy()
        self.n = len(candles)

        # per-date [start, end) bounds and rth_open_idx
        self.date_start: dict[Any, int] = {}
        self.date_end: dict[Any, int] = {}
        self.rth_open_idx: dict[Any, int] = {}
        prev = None
        start = 0
        for i in range(self.n):
            d = self.date[i]
            if d != prev:
                if prev is not None:
                    self.date_end[prev] = i
                self.date_start[d] = i
                prev = d
        if prev is not None:
            self.date_end[prev] = self.n
        for d, s in self.date_start.items():
            e = self.date_end[d]
            ro = None
            for i in range(s, e):
                if self.tod[i] >= RTH_OPEN:
                    ro = i
                    break
            if ro is not None:
                self.rth_open_idx[d] = ro

    def idx_for_utc_ns(self, ns: int) -> Optional[int]:
        j = int(np.searchsorted(self.ts_utc_ns, ns))
        if 0 <= j < self.n and self.ts_utc_ns[j] == ns:
            return j
        return None


# ===================================================================
# Daily regime precompute (causal: every series shifted to PRIOR day)
# ===================================================================

def build_daily_context() -> pd.DataFrame:
    """Per-date regime context using ONLY information available at 9:30.

    Returns a DataFrame indexed by date with:
      atr14            : 14-day ATR through the PRIOR session (shift 1).
      ema20, ema50     : daily-close EMAs through the PRIOR session (shift 1).
      macro_trend      : {'up','down','flat'} from price-vs-EMA + EMA slope (prior).
      prior_vp_poc/vah/val/width : PRIOR trading day's RTH volume profile (lag-1).
      vixy_regime, prior_day_type, gap_from_prior_close, rth_open : same-day open info.
    """
    td = pd.read_csv(TRADING_DAYS)
    td['date'] = pd.to_datetime(td['date']).dt.date
    td = td.sort_values('date').reset_index(drop=True)

    # True range from daily RTH OHLC; ATR14 through prior day (shift 1).
    h, l, c = td['rth_high'], td['rth_low'], td['rth_close']
    prev_close = c.shift(1)
    tr = pd.concat([(h - l), (h - prev_close).abs(), (l - prev_close).abs()], axis=1).max(axis=1)
    td['atr14'] = tr.rolling(14, min_periods=5).mean().shift(1)

    td['ema20'] = c.ewm(span=20, adjust=False).mean().shift(1)
    td['ema50'] = c.ewm(span=50, adjust=False).mean().shift(1)
    ema20_slope = (td['ema20'] - td['ema20'].shift(1))
    # macro_trend: price (prior close) vs ema, confirmed by ema20 slope sign.
    pc = prev_close
    up = (pc > td['ema20']) & (td['ema20'] > td['ema50']) & (ema20_slope > 0)
    dn = (pc < td['ema20']) & (td['ema20'] < td['ema50']) & (ema20_slope < 0)
    td['macro_trend'] = np.where(up, 'up', np.where(dn, 'down', 'flat'))

    # lag-1 volume profile
    vp = pd.read_csv(DAILY_VP)
    vp['date'] = pd.to_datetime(vp['date']).dt.date
    vp = vp.sort_values('date').reset_index(drop=True)
    vp['prior_vp_poc'] = vp['poc'].shift(1)
    vp['prior_vp_vah'] = vp['vah'].shift(1)
    vp['prior_vp_val'] = vp['val'].shift(1)
    vp['prior_vp_width'] = vp['va_width'].shift(1)
    vp_lag = vp[['date', 'prior_vp_poc', 'prior_vp_vah', 'prior_vp_val', 'prior_vp_width']]

    keep = ['date', 'atr14', 'ema20', 'ema50', 'macro_trend',
            'vixy_regime', 'prior_day_type', 'gap_from_prior_close', 'rth_open',
            'or_5min_high', 'or_5min_low', 'or_15min_high', 'or_15min_low',
            'or_45min_high', 'or_45min_low']
    ctx = td[keep].merge(vp_lag, on='date', how='left')
    return ctx.set_index('date')


# ===================================================================
# Level universe per date (causal availability via filter_trade_date_levels)
# ===================================================================

def load_levels_by_date() -> dict[Any, pd.DataFrame]:
    liqu = pd.read_csv(LIQUIDITY)
    liqu['date'] = pd.to_datetime(liqu['date']).dt.date
    out: dict[Any, pd.DataFrame] = {}
    for d, grp in liqu.groupby('date'):
        out[d] = grp.reset_index(drop=True)
    return out


def parse_avail_time(val: Any) -> Optional[dtime]:
    s = str(val).strip().lower()
    if s in ('', 'nan', 'none', 'open'):
        return None
    try:
        hh, mm = s.split(':')
        return dtime(int(hh), int(mm))
    except (ValueError, AttributeError):
        return None


def build_level_candidates(
    day_levels: Optional[pd.DataFrame],
    entry_tod: dtime,
    ctx_row: pd.Series,
    rth_lo: float,
    rth_hi: float,
) -> list[dict]:
    """All level candidates valid AS-OF entry time-of-day.

    Each candidate: {price, group, side, is_stop_liquidity, is_htf, htf_tf,
                     fvg_dir, fvg_top, fvg_bottom, bars_old}.
    Mean-reversion magnets (VWAP/POC) are added by the caller, not here.

    Availability gate: only levels whose `available_time` <= entry_tod (the same
    gate the production pipeline uses) — prevents e.g. OR levels (avail 09:45)
    leaking into pre-09:45 signals.
    """
    cands: list[dict] = []
    if day_levels is not None and not day_levels.empty:
        flt = filter_trade_date_levels(day_levels)
        for _, r in flt.iterrows():
            px = r.get('price')
            if px is None or (isinstance(px, float) and np.isnan(px)):
                continue
            at = parse_avail_time(r.get('available_time'))
            if at is not None and entry_tod < at:
                continue
            group = str(r.get('group'))
            tf = r.get('timeframe')
            is_htf = pd.notna(tf) and str(tf).strip() not in ('', 'nan', 'none')
            fvg_dir = str(r.get('fvg_direction')) if is_htf else ''
            side = str(r.get('side'))
            bars_old = r.get('bars_old')
            cands.append({
                'price': float(px),
                'group': group,
                'side': side,
                'is_stop_liquidity': group in STOP_LIQUIDITY_GROUPS,
                'is_htf': bool(is_htf),
                'htf_tf': str(tf) if is_htf else '',
                'fvg_dir': fvg_dir,
                'fvg_top': float(r['fvg_top']) if is_htf and pd.notna(r.get('fvg_top')) else np.nan,
                'fvg_bottom': float(r['fvg_bottom']) if is_htf and pd.notna(r.get('fvg_bottom')) else np.nan,
                'bars_old': float(bars_old) if pd.notna(bars_old) else np.nan,
            })

    # Round-number levels within the session range (stop-liquidity, always avail).
    for grid, tag in ((ROUND_100, 'round_100'), (ROUND_50, 'round_50')):
        lo = int(np.floor(rth_lo / grid)) * grid
        hi = int(np.ceil(rth_hi / grid)) * grid
        p = lo
        while p <= hi:
            cands.append({
                'price': float(p), 'group': tag, 'side': 'both',
                'is_stop_liquidity': True, 'is_htf': False, 'htf_tf': '',
                'fvg_dir': '', 'fvg_top': np.nan, 'fvg_bottom': np.nan,
                'bars_old': np.nan,
            })
            p += grid
    return cands


# ===================================================================
# §4.1 Intraday sweep + recency  (as-of: RTH bars 9:30 -> fvg_created)
# ===================================================================

def _bars_since_sweep_bucket(b: Optional[int]) -> str:
    if b is None:
        return 'none'
    if b <= 5:
        return '0-5'
    if b <= 15:
        return '5-15'
    if b <= 60:
        return '15-60'
    return '>60'


def detect_swept_level(
    ci: CandleIndex, d: Any, created_idx: int, direction: str,
    fvg_top: float, fvg_bottom: float, fvg_size: float,
    cands: list[dict],
) -> dict:
    """Find the most-recent STOP-LIQUIDITY level interaction the FVG sits at.

    As-of window: RTH bars [rth_open, created_idx) ONLY — the interaction must
    precede the FVG's formation, so no information after the FVG is read.

    Per Phil: an interaction does NOT require a strict wick-past-and-close-back.
    A "reach" of the level counts as the swept interaction; `sweep_reclaim`
    records whether that bar also closed back on the favorable side (grab) vs
    merely tagged/penetrated it (tag). Phase B can split reclaim vs tag.

    long  signal -> support-type level reached (low<=L); reclaim = close>L.
    short signal -> resistance-type level reached (high>=L); reclaim = close<L.

    "Sits at": level price within FVG zone padded by max(LEVEL_PAD, 0.5*fvg_size).
    Returns swept(bool), bars_since_sweep, provenance, level price, reclaim flag.
    """
    pad = max(LEVEL_PAD, 0.5 * fvg_size)
    zone_lo, zone_hi = fvg_bottom - pad, fvg_top + pad
    ro = ci.rth_open_idx.get(d)
    out = {
        'swept': False, 'bars_since_sweep': None, 'bars_since_sweep_bucket': 'none',
        'swept_level_provenance': '', 'swept_level_price': np.nan,
        'sweep_reclaim': None, 'sweep_type': 'none',
    }
    if ro is None or created_idx <= ro:
        return out

    # candidate levels coinciding with the FVG zone (stop-liquidity only)
    coincident = [c for c in cands
                  if c['is_stop_liquidity'] and zone_lo <= c['price'] <= zone_hi]
    if not coincident:
        return out

    best_sweep_idx = -1
    best = None
    for c in coincident:
        L = c['price']
        for j in range(ro, created_idx):
            if direction == 'long':
                reached = ci.low[j] <= L
                reclaim = reached and ci.close[j] > L
            else:
                reached = ci.high[j] >= L
                reclaim = reached and ci.close[j] < L
            if reached and j > best_sweep_idx:
                best_sweep_idx = j
                best = (c, reclaim)
    if best is None:
        return out

    c, reclaim = best
    out['swept'] = True
    out['bars_since_sweep'] = created_idx - best_sweep_idx
    out['bars_since_sweep_bucket'] = _bars_since_sweep_bucket(out['bars_since_sweep'])
    out['swept_level_provenance'] = c['group']
    out['swept_level_price'] = c['price']
    out['sweep_reclaim'] = bool(reclaim)
    out['sweep_type'] = 'reclaim' if reclaim else 'tag'
    return out


# ===================================================================
# §4.2 break -> retest timing  (as-of: bars [created, entry])
# ===================================================================

def break_to_retest(
    ci: CandleIndex, created_idx: int, entry_idx: int, direction: str,
    fvg_top: float, fvg_bottom: float,
) -> dict:
    """bars from structural break (first close beyond FVG far edge in trade
    direction, the displacement leg) to the FVGC entry candle.

    As-of window: bars [created_idx, entry_idx] only. Causal by construction.
    NA when no break precedes entry (entry is then not a true break-&-retest).
    """
    break_idx = None
    for j in range(created_idx, entry_idx + 1):
        if direction == 'long' and ci.close[j] > fvg_top:
            break_idx = j
            break
        if direction == 'short' and ci.close[j] < fvg_bottom:
            break_idx = j
            break
    if break_idx is None:
        return {'has_break': False, 'bars_break_to_retest': None,
                'bars_break_to_retest_bucket': 'none',
                'break_to_retest_min': None, 'retest_within_10min': None}
    b = entry_idx - break_idx
    mins = b * 0.5  # 30s bars
    if b <= 1:
        bucket = '0-1'
    elif b <= 3:
        bucket = '2-3'
    elif b <= 6:
        bucket = '4-6'
    elif b <= 12:
        bucket = '7-12'
    else:
        bucket = '>12'
    return {'has_break': True, 'bars_break_to_retest': b,
            'bars_break_to_retest_bucket': bucket,
            'break_to_retest_min': mins,
            'retest_within_10min': b <= 20}  # 10 min = 20 x 30s bars


# ===================================================================
# §4.3 next untested magnet  (as-of: RTH bars 9:30 -> entry for untested check)
# ===================================================================

def level_untested_asof(ci: CandleIndex, d: Any, entry_idx: int, price: float) -> bool:
    """True if no RTH bar in [rth_open, entry_idx) traded through `price`."""
    ro = ci.rth_open_idx.get(d)
    if ro is None:
        return True
    for j in range(ro, entry_idx):
        if ci.low[j] <= price <= ci.high[j]:
            return False
    return True


def next_magnet(
    ci: CandleIndex, d: Any, entry_idx: int, entry: float, direction: str,
    sl_dist: float, fvg_size: float, atr: float,
    cands: list[dict], mr_magnets: list[tuple[float, str]],
) -> dict:
    """Nearest UNTESTED magnet past entry in trade direction.

    Magnet universe = stop-liquidity levels + mean-reversion magnets (VWAP/POC/VA).
    As-of: untested status uses RTH bars up to entry only; all level prices are
    known at-or-before entry. clean_runway = no opposing level between entry and
    the magnet.
    """
    all_mags: list[tuple[float, str]] = [(c['price'], c['group']) for c in cands]
    all_mags += mr_magnets

    if direction == 'long':
        ahead = [(p, g) for p, g in all_mags if p > entry]
        ahead.sort(key=lambda x: x[0])
    else:
        ahead = [(p, g) for p, g in all_mags if p < entry]
        ahead.sort(key=lambda x: -x[0])

    magnet_price = None
    magnet_group = None
    for p, g in ahead:
        if level_untested_asof(ci, d, entry_idx, p):
            magnet_price, magnet_group = p, g
            break

    out = {
        'magnet_price': np.nan, 'magnet_group': '', 'magnet_dist_pts': np.nan,
        'magnet_dist_R': np.nan, 'magnet_dist_per_fvg': np.nan,
        'magnet_dist_per_atr': np.nan, 'clean_runway': None,
    }
    if magnet_price is None:
        return out
    dist = abs(magnet_price - entry)
    out['magnet_price'] = magnet_price
    out['magnet_group'] = magnet_group
    out['magnet_dist_pts'] = dist
    out['magnet_dist_R'] = dist / sl_dist if sl_dist and sl_dist > 0 else np.nan
    out['magnet_dist_per_fvg'] = dist / fvg_size if fvg_size > 0 else np.nan
    out['magnet_dist_per_atr'] = dist / atr if atr and atr > 0 else np.nan

    # clean runway: no OTHER level strictly between entry and the magnet
    blocked = False
    lo, hi = (entry, magnet_price) if entry < magnet_price else (magnet_price, entry)
    for p, g in all_mags:
        if lo < p < hi and abs(p - magnet_price) > 1e-9:
            blocked = True
            break
    out['clean_runway'] = not blocked
    return out


# ===================================================================
# §4.5 level-state qualifiers for the swept level (as-of RTH -> entry)
# ===================================================================

def level_state(
    ci: CandleIndex, d: Any, entry_idx: int, level_price: float, pad: float,
) -> dict:
    """virgin / touch_count for the swept level using RTH bars [rth_open, entry)."""
    ro = ci.rth_open_idx.get(d)
    out = {'level_touch_count': None, 'level_virgin': None}
    if ro is None or np.isnan(level_price):
        return out
    touches = 0
    for j in range(ro, entry_idx):
        if ci.low[j] - pad <= level_price <= ci.high[j] + pad:
            touches += 1
    out['level_touch_count'] = touches
    out['level_virgin'] = touches <= 1
    return out


# ===================================================================
# §4.6 nested HTF gap  (as-of: HTF FVG pre-exists; position from entry price)
# ===================================================================

def nested_htf(entry: float, direction: str, cands: list[dict]) -> dict:
    """Is entry inside an unfilled HTF FVG, and where within it?

    position_within_gap: 0 at the near (entry-side) edge, 1 at the far edge in
    the trade-continuation direction. High position => trading INTO the far edge
    (likely HTF resistance/fade); low position => open runway toward far edge.
    As-of: HTF FVG bounds are pre-session/pre-entry; entry price is known. Causal.
    """
    out = {'inside_htf_fvg': False, 'htf_nest_tf': '', 'htf_position_within_gap': np.nan,
           'htf_aligned': None}
    best = None
    for c in cands:
        if not c['is_htf']:
            continue
        top, bot = c['fvg_top'], c['fvg_bottom']
        if np.isnan(top) or np.isnan(bot):
            continue
        if bot <= entry <= top:
            width = top - bot
            if width <= 0:
                continue
            # far edge in trade direction
            if direction == 'long':
                pos = (entry - bot) / width  # 0 at bottom(near), 1 at top(far)
                aligned = (c['fvg_dir'] == 'bullish')
            else:
                pos = (top - entry) / width  # 0 at top(near), 1 at bottom(far)
                aligned = (c['fvg_dir'] == 'bearish')
            # prefer the smallest-TF nesting? keep the one with widest gap (most structural)
            if best is None or width > best[0]:
                best = (width, c['htf_tf'], pos, aligned)
    if best is not None:
        out['inside_htf_fvg'] = True
        out['htf_nest_tf'] = best[1]
        out['htf_position_within_gap'] = round(best[2], 4)
        out['htf_aligned'] = bool(best[3])
    return out


# ===================================================================
# Developing VP  (as-of: RTH bars 9:30 -> entry)
# ===================================================================

def developing_vp(ci_df_day: pd.DataFrame) -> Optional[dict]:
    """VP from this session's RTH bars 9:30 -> entry (developing, causal)."""
    if ci_df_day is None or ci_df_day.empty:
        return None
    return compute_volume_profile(ci_df_day, bucket_size=1.0, value_area_pct=0.70)


# ===================================================================
# Driver
# ===================================================================

def va_position(price: float, vah: float, val: float) -> str:
    if np.isnan(vah) or np.isnan(val):
        return 'unknown'
    if price > vah:
        return 'above'
    if price < val:
        return 'below'
    return 'inside'


def enrich(sample: Optional[int] = None) -> pd.DataFrame:
    t0 = _time.time()
    candles = load_candles(CONS_30S)
    ci = CandleIndex(candles)
    print(f"  CandleIndex built: {_time.time()-t0:.1f}s, n={ci.n:,}")

    ctx = build_daily_context()
    levels_by_date = load_levels_by_date()
    print(f"  Context: {len(ctx)} days, levels: {len(levels_by_date)} days")

    sig = pd.read_csv(BASELINE)
    sig['ts'] = pd.to_datetime(sig['timestamp'])
    sig['fvg_created_ts'] = pd.to_datetime(sig['fvg_created_at'])
    if sample:
        sig = sig.iloc[:sample].copy()

    def to_utc_ns(ts: pd.Timestamp) -> int:
        """NY-local naive (or tz-aware) timestamp -> UTC ns (matches ci.ts_utc_ns)."""
        if ts.tzinfo is None:
            ts = ts.tz_localize('America/New_York')
        return int(ts.tz_convert('UTC').value)

    align_fail = 0     # signals whose entry_idx doesn't match its timestamp
    created_fail = 0   # signals whose fvg_created_at didn't resolve to a bar
    rows = []
    for _, s in sig.iterrows():
        entry_idx = int(s['entry_idx'])
        d = s['ts'].date()
        direction = str(s['direction'])
        entry = float(s['entry_price'])
        fvg_top = float(s['fvg_top'])
        fvg_bottom = float(s['fvg_bottom'])
        fvg_size = abs(fvg_top - fvg_bottom)
        try:
            sl_dist = float(s.get('sl_dist'))
        except (TypeError, ValueError):
            sl_dist = np.nan

        # entry_idx alignment guard: bar at entry_idx must equal the signal bar.
        if not (0 <= entry_idx < ci.n) or ci.ts_utc_ns[entry_idx] != to_utc_ns(s['ts']):
            align_fail += 1
            continue  # skip mis-indexed signal rather than emit bad features

        created_idx = ci.idx_for_utc_ns(to_utc_ns(s['fvg_created_ts']))
        if created_idx is None:
            created_idx = max(0, entry_idx - 1)
            created_fail += 1

        ctx_row = ctx.loc[d] if d in ctx.index else None
        atr = float(ctx_row['atr14']) if ctx_row is not None and pd.notna(ctx_row['atr14']) else np.nan

        # day RTH slice up to entry (for round-grid range, dev VP, untested checks)
        ro = ci.rth_open_idx.get(d)
        rth_lo = float(np.min(ci.low[ro:entry_idx + 1])) if ro is not None else entry
        rth_hi = float(np.max(ci.high[ro:entry_idx + 1])) if ro is not None else entry

        entry_tod = s['ts'].time()
        day_levels = levels_by_date.get(d)
        cands = build_level_candidates(day_levels, entry_tod, ctx_row, rth_lo, rth_hi)

        # --- mean-reversion magnets (VWAP, lag-1 VP, developing VP) ---
        mr_magnets: list[tuple[float, str]] = []
        # session VWAP as-of entry
        vwap_val = np.nan
        if ro is not None:
            day_df = candles.iloc[ci.date_start[d]:ci.date_end[d]]
            vser = session_vwap(day_df)
            # value at entry_idx (absolute) -> position within day_df
            rel = entry_idx - ci.date_start[d]
            if 0 <= rel < len(vser):
                vwap_val = float(vser.iloc[rel]) if pd.notna(vser.iloc[rel]) else np.nan
        if not np.isnan(vwap_val):
            mr_magnets.append((vwap_val, 'vwap'))

        prior_poc = float(ctx_row['prior_vp_poc']) if ctx_row is not None and pd.notna(ctx_row.get('prior_vp_poc')) else np.nan
        prior_vah = float(ctx_row['prior_vp_vah']) if ctx_row is not None and pd.notna(ctx_row.get('prior_vp_vah')) else np.nan
        prior_val = float(ctx_row['prior_vp_val']) if ctx_row is not None and pd.notna(ctx_row.get('prior_vp_val')) else np.nan
        for p, tag in ((prior_poc, 'prior_poc'), (prior_vah, 'prior_vah'), (prior_val, 'prior_val')):
            if not np.isnan(p):
                mr_magnets.append((p, tag))

        # developing VP up to entry
        dev = None
        if ro is not None:
            day_rth = candles.iloc[ro:entry_idx + 1]
            dev = developing_vp(day_rth)
        dev_poc = dev['poc'] if dev else np.nan
        dev_vah = dev['vah'] if dev else np.nan
        dev_val = dev['val'] if dev else np.nan
        if dev:
            mr_magnets.append((dev_poc, 'dev_poc'))

        # --- features ---
        sw = detect_swept_level(ci, d, created_idx, direction, fvg_top, fvg_bottom, fvg_size, cands)
        br = break_to_retest(ci, created_idx, entry_idx, direction, fvg_top, fvg_bottom)
        mag = next_magnet(ci, d, entry_idx, entry, direction, sl_dist, fvg_size, atr, cands, mr_magnets)
        pad = max(LEVEL_PAD, 0.5 * fvg_size)
        lst = level_state(ci, d, entry_idx, sw['swept_level_price'], pad)
        nh = nested_htf(entry, direction, cands)

        # VWAP location
        vwap_dist = (entry - vwap_val) if not np.isnan(vwap_val) else np.nan
        if direction == 'short' and not np.isnan(vwap_dist):
            vwap_dist_signed = -vwap_dist  # +ve = in trade-favorable side (above for short)
        else:
            vwap_dist_signed = vwap_dist
        vwap_above = (entry > vwap_val) if not np.isnan(vwap_val) else None
        r0_ge_10 = (abs(vwap_dist) >= 10.0) if not np.isnan(vwap_dist) else None

        # VA position (lag-1 and developing)
        va_pos_prior = va_position(entry, prior_vah, prior_val)
        va_pos_dev = va_position(entry, dev_vah, dev_val) if dev else 'unknown'

        # confluence stack: distinct groups within FVG zone +/- 10pt
        stack_groups = set()
        for c in cands:
            if abs(c['price'] - (fvg_top + fvg_bottom) / 2) <= 10.0:
                stack_groups.add(c['group'])
        confluence_stack = len(stack_groups)

        # regime: intraday — open vs prior VA, OR width (availability-gated), price vs dev VWAP/POC
        rth_open_px = float(ctx_row['rth_open']) if ctx_row is not None and pd.notna(ctx_row.get('rth_open')) else np.nan
        open_vs_prior_va = va_position(rth_open_px, prior_vah, prior_val)
        # OR width available as-of entry: widest OR window whose end <= entry_tod
        or_width = np.nan
        if ctx_row is not None:
            if entry_tod >= dtime(10, 15) and pd.notna(ctx_row.get('or_45min_high')):
                or_width = float(ctx_row['or_45min_high']) - float(ctx_row['or_45min_low'])
            elif entry_tod >= dtime(9, 45) and pd.notna(ctx_row.get('or_15min_high')):
                or_width = float(ctx_row['or_15min_high']) - float(ctx_row['or_15min_low'])
            elif entry_tod >= dtime(9, 35) and pd.notna(ctx_row.get('or_5min_high')):
                or_width = float(ctx_row['or_5min_high']) - float(ctx_row['or_5min_low'])
        price_vs_dev_vwap = (entry > vwap_val) if not np.isnan(vwap_val) else None
        price_vs_dev_poc = (entry > dev_poc) if dev else None

        macro_trend = str(ctx_row['macro_trend']) if ctx_row is not None else 'flat'
        vixy_regime = str(ctx_row['vixy_regime']) if ctx_row is not None and pd.notna(ctx_row.get('vixy_regime')) else 'unknown'
        prior_day_type = str(ctx_row['prior_day_type']) if ctx_row is not None and pd.notna(ctx_row.get('prior_day_type')) else 'unknown'

        # direction x regime alignment
        if macro_trend == 'up':
            regime_alignment = 'aligned' if direction == 'long' else 'counter'
        elif macro_trend == 'down':
            regime_alignment = 'aligned' if direction == 'short' else 'counter'
        else:
            regime_alignment = 'flat'

        row = {
            **s.drop(labels=['ts', 'fvg_created_ts']).to_dict(),
            'created_idx': created_idx,
            'atr14': atr,
            # 4.1
            **sw,
            # 4.2
            **br,
            # 4.3
            **mag,
            # 4.4 vwap / VA
            'vwap': vwap_val, 'vwap_dist_pts': vwap_dist, 'vwap_dist_signed': vwap_dist_signed,
            'vwap_above': vwap_above, 'r0_ge_10pt': r0_ge_10,
            'va_pos_prior': va_pos_prior, 'va_pos_dev': va_pos_dev,
            # 4.5
            **lst, 'confluence_stack': confluence_stack,
            # 4.6
            **nh,
            # 4.7 regime
            'macro_trend': macro_trend, 'vixy_regime': vixy_regime,
            'prior_day_type': prior_day_type, 'regime_alignment': regime_alignment,
            'open_vs_prior_va': open_vs_prior_va, 'or_width_asof': or_width,
            'price_above_dev_vwap': price_vs_dev_vwap, 'price_above_dev_poc': price_vs_dev_poc,
            # dev VP raw
            'dev_poc': dev_poc, 'dev_vah': dev_vah, 'dev_val': dev_val,
            'prior_vp_poc': prior_poc, 'prior_vp_vah': prior_vah, 'prior_vp_val': prior_val,
        }
        rows.append(row)

    out = pd.DataFrame(rows)
    print(f"  Enriched {len(out)} signals in {_time.time()-t0:.1f}s "
          f"(entry_idx misaligned/skipped: {align_fail}, created_idx fallback: {created_fail})")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--sample', type=int, default=None)
    ap.add_argument('--out', type=str, default=str(RESULTS_DIR / 'signals_enriched.csv'))
    args = ap.parse_args()

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    df = enrich(sample=args.sample)
    df.to_csv(args.out, index=False)
    print(f"Wrote {len(df)} rows -> {args.out}")


if __name__ == '__main__':
    main()
