// Auto-generated by tools/morning_briefing.py --rewrite-js-from-json.
window.BRIEFING_DATA = {
  "schema_version": 1,
  "meta": {
    "date": "2026-05-19",
    "day_of_week": "Tuesday",
    "generated_at_et": "2026-05-19T09:27:32.446827-04:00",
    "generated_at_pt": "2026-05-19T06:27:32.446827-07:00",
    "mode": "live"
  },
  "freshness": [],
  "or_forecast": {
    "available": true,
    "point_pts": 208.3,
    "lo80_pts": 135.6,
    "hi80_pts": 316.2,
    "baseline_pts": 117.6,
    "quintile": "Q4 (65th pct)",
    "tier_label": "Wide \u2014 favor full size on confluence setups",
    "tier_level": "wide",
    "feature_date": "2026-02-20",
    "is_stale": true,
    "overrides": [
      "overnight_range",
      "gap_abs",
      "gap_atr_ratio",
      "prior_day_range",
      "prior_day_close_position",
      "atr_5d",
      "atr_20d",
      "atr_ratio_5_20",
      "pdr_pctile_20d",
      "nr4_flag",
      "nr7_flag",
      "vixy_prior_close",
      "vix_5d_chg"
    ],
    "drivers": [
      {
        "factor": "overnight_range",
        "value": 357.5,
        "z": 1.76,
        "delta_pts": 45.9
      },
      {
        "factor": "atr_20d",
        "value": 357.15,
        "z": 1.2,
        "delta_pts": 27.9
      },
      {
        "factor": "gap_abs",
        "value": 235.75,
        "z": 1.45,
        "delta_pts": -12.4
      },
      {
        "factor": "atr_5d",
        "value": 461.3,
        "z": 1.8,
        "delta_pts": -11.8
      },
      {
        "factor": "atr_ratio_5_20",
        "value": 1.292,
        "z": 1.18,
        "delta_pts": 11.7
      },
      {
        "factor": "prior_day_range",
        "value": 541.5,
        "z": 1.89,
        "delta_pts": 10.6
      }
    ],
    "perf": {
      "n": "712",
      "mae_pts": "43.77574530141055",
      "mape_pct": "32.486884988393626",
      "r2": "0.11249480347027607",
      "spearman_rho": "0.5988155638556552",
      "interval_coverage_80": "0.7415730337078652",
      "model": "cold_start",
      "n_features": "17"
    },
    "narrative": "The <b>208-pt forecast (Wide tier, Q4/65th pct)</b> is driven primarily by a wide overnight range (+46 pts contribution) and elevated 20d ATR (+28 pts). Today favors <b>full size on confluence setups</b> \u2014 the 80% interval spans 136\u2013316 pts, so confirm actual OR width at 10:15 before committing to extended targets."
  },
  "calendar": {
    "day_of_week": "Tuesday",
    "dow_note": "Tuesday is the weakest day in the sample (WR ~49.2%). Stay selective.",
    "unknown": false,
    "is_fomc_week": false,
    "events": [
      {
        "event": "Pending Home Sales m/m",
        "time_et": "14:00",
        "impact": "Medium",
        "currency": ""
      }
    ],
    "narrative": "Calendar is <b>clean for the RTH session</b> \u2014 Pending Home Sales at 14:00 ET is post-session and medium impact only. <b>Tuesday structural headwind</b> (WR ~49.2%) is the primary drag; require higher confluence count before entry and stay selective."
  },
  "pre_open": {
    "current_price": 28863.0,
    "current_price_ts": "09:17 ET",
    "prior_rth": {
      "close": 29098.75,
      "open": 29338.25,
      "high": 29356.25,
      "low": 28814.75,
      "close_position": 0.5244690674053555,
      "label": null
    },
    "overnight": {
      "high": 29188.5,
      "low": 28831.0,
      "range": 357.5,
      "direction": "down",
      "tight": false,
      "wide": true
    },
    "asia": {
      "high": 29188.5,
      "low": 28885.0
    },
    "london": {
      "high": 29125.25,
      "low": 28836.0
    },
    "gap": {
      "pts": -235.75,
      "pct": -0.8101722582585162,
      "direction": "gap_down"
    },
    "data_notes": [],
    "narrative": "Overnight sold off <b>357.5 pts from 29188 to 28831</b> (wide top-20%, directionally down), with a <b>large gap-down of 235.75 pts (\u22120.81%)</b> setting a bearish bias into the open. Current price 28863 is clustered near overnight lows \u2014 the key 9:30 question is whether sellers push through the ON low or buyers defend for a gap-fade long."
  },
  "levels": {
    "scope_pts": 100,
    "above": [
      {
        "group": "htf_fvg_15m",
        "label": "15m FVG (bearish)",
        "price": 28879.5,
        "distance_pts": 16.5,
        "direction": "above",
        "tier": "A",
        "hit_rate_45m_pct": 26.2,
        "wr_as_magnet_pct": 58.4,
        "pf_as_magnet": 1.51,
        "below_baseline": false
      },
      {
        "group": "asia",
        "label": "Asia low",
        "price": 28885.0,
        "distance_pts": 22.0,
        "direction": "above",
        "tier": "A",
        "hit_rate_45m_pct": 59.2,
        "wr_as_magnet_pct": 54.2,
        "pf_as_magnet": 1.22,
        "below_baseline": false
      }
    ],
    "below": [
      {
        "group": "london",
        "label": "London low",
        "price": 28836.0,
        "distance_pts": -27.0,
        "direction": "below",
        "tier": "C",
        "hit_rate_45m_pct": 54.3,
        "wr_as_magnet_pct": 47.4,
        "pf_as_magnet": 0.95,
        "below_baseline": true
      },
      {
        "group": "overnight",
        "label": "Overnight low",
        "price": 28831.0,
        "distance_pts": -32.0,
        "direction": "below",
        "tier": "C",
        "hit_rate_45m_pct": 41.1,
        "wr_as_magnet_pct": 48.7,
        "pf_as_magnet": 0.86,
        "below_baseline": true
      },
      {
        "group": "prev_day",
        "label": "Prev day low",
        "price": 28814.75,
        "distance_pts": -48.25,
        "direction": "below",
        "tier": "A",
        "hit_rate_45m_pct": 40.6,
        "wr_as_magnet_pct": 57.1,
        "pf_as_magnet": 1.45,
        "below_baseline": false
      }
    ],
    "narrative": "<b>Short-side draw: PDL at 28814.75</b> is the highest-quality target below (WR 57.1%, PF 1.45 at \u221248 pts) \u2014 London low and ON low are below-baseline magnets and better treated as waypoints than clean TPs. <b>Long-side resistance: bearish 15m FVG at 28879.5</b> (+16.5 pts, WR 58.4%) stacks immediately below Asia low at 28885, creating a dense 28879\u201328885 cluster that caps any bounce play."
  },
  "factors": {
    "active": [
      "elevated_vixy",
      "gap_down",
      "no_pre_rth_news",
      "no_red_folder",
      "not_fomc_week",
      "overnight_down",
      "tuesday",
      "wide_overnight"
    ],
    "inactive": [
      "entry_inside_prior_day_value_area",
      "friday",
      "gap_up",
      "has_pre_rth_news",
      "has_red_folder",
      "is_fomc_week",
      "low_vixy",
      "monday",
      "normal_vixy",
      "overnight_up",
      "prior_day_down",
      "prior_day_up",
      "thursday",
      "tight_overnight",
      "wednesday"
    ],
    "unknown": [],
    "narrative": "<b>No pre-RTH news (+21pp to M1 Long)</b> and wide overnight with gap-down create a textbook fade-the-gap setup alongside a clean short bias. The <b>elevated VIX and Tuesday bias</b> are the two headwinds \u2014 require 3+ confluence before entry and skip marginal setups. The clean calendar (no red folder) activates the structural Macro 1 short edge."
  },
  "armed_edges": [],
  "watch_list": [
    {
      "stars": "\u2605\u2605\u2605",
      "factors": [
        "macro_w1",
        "no_red_folder",
        "wide_45min_or"
      ],
      "n": 64,
      "wr_pct": 75.0,
      "pf": 3.21,
      "p_wr": 0.0,
      "pre_matched": [
        "no_red_folder"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "no_pre_rth_news",
        "wide_45min_or"
      ],
      "n": 67,
      "wr_pct": 74.6,
      "pf": 3.27,
      "p_wr": 0.0,
      "pre_matched": [
        "no_pre_rth_news"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "short_only",
        "wide_45min_or"
      ],
      "n": 51,
      "wr_pct": 74.5,
      "pf": 3.07,
      "p_wr": 0.0,
      "pre_matched": [],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "wide_45min_or"
      ],
      "n": 77,
      "wr_pct": 72.7,
      "pf": 2.84,
      "p_wr": 0.0,
      "pre_matched": [],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "not_fomc_week",
        "wide_45min_or"
      ],
      "n": 67,
      "wr_pct": 70.1,
      "pf": 2.47,
      "p_wr": 0.001,
      "pre_matched": [
        "not_fomc_week"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "bearish_930",
        "macro_w1",
        "overnight_down"
      ],
      "n": 64,
      "wr_pct": 68.8,
      "pf": 2.3,
      "p_wr": 0.003,
      "pre_matched": [
        "overnight_down"
      ],
      "post_needed": [
        {
          "factor": "bearish_930",
          "desc": "9:30 candle closed bearish"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "gap_down",
        "short_only",
        "wide_45min_or"
      ],
      "n": 92,
      "wr_pct": 67.4,
      "pf": 2.18,
      "p_wr": 0.0,
      "pre_matched": [
        "gap_down"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "bearish_930",
        "large_930_candle",
        "wide_overnight"
      ],
      "n": 61,
      "wr_pct": 67.2,
      "pf": 2.24,
      "p_wr": 0.01,
      "pre_matched": [
        "wide_overnight"
      ],
      "post_needed": [
        {
          "factor": "bearish_930",
          "desc": "9:30 candle closed bearish"
        },
        {
          "factor": "large_930_candle",
          "desc": "9:30 candle range in top 20%"
        }
      ]
    }
  ],
  "w1_short_confluence": {
    "preopen_count": 3,
    "active_factors": [
      "gap_down",
      "large_gap",
      "overnight_down"
    ],
    "tier": null
  },
  "matrix_plays": [
    {
      "name": "M1 Short",
      "direction": "short",
      "window": "9:30-9:45",
      "veto_active": false,
      "active_vetoes": [],
      "preopen_count": 1,
      "max_preopen": 5,
      "preopen_active": [
        {
          "id": "gap_large_down",
          "desc": "Gap < -100 pts",
          "lift_pp": 19.0
        }
      ],
      "post_pending": [
        {
          "id": "bear_930",
          "when": "9:31",
          "desc": "Bearish 9:30 1-min candle",
          "lift_pp": 21.3
        },
        {
          "id": "c930_body_top_q",
          "when": "9:31",
          "desc": "9:30 candle body in top quartile (>=23 pts)",
          "lift_pp": 15.6
        }
      ],
      "projection": {
        "min_count": 1,
        "max_count": 3,
        "min_tier": {
          "action": "SKIP",
          "note": "no edge"
        },
        "max_tier": {
          "action": "TAKE full size, runner mode",
          "note": "~73% WR, PF 2.71"
        },
        "locked": false
      },
      "expectancy": {
        "tradeable_threshold": 2,
        "setup_pct_of_all_days": 36.0,
        "fire_rate_pct": 23.0,
        "ev_per_setup_day_R": 0.253,
        "fire_rate_now_pct": 21.1,
        "fire_rate_max_pct": 20.2
      },
      "extra_note": "RUNNER EXIT DOCTRINE: TP@5R no-BE is the optimal exit (PF 3+). BE management caps the edge. Do not apply M2/M3 long-style BE@1R here.",
      "notion_url": "https://www.notion.so/33de2f0e776081889879c4dcbd495996",
      "narrative": "<b>1/5 preopen active (gap_large_down)</b> \u2014 needs bearish 9:30 candle + large body at 9:31 to reach take tier. Today's large gap-down is structurally supportive; if sellers open aggressively with a momentum candle, this becomes a <b>full-size runner trade (no BE, target 5R)</b> targeting PDL at 28814.75."
    },
    {
      "name": "M1 Long",
      "direction": "long",
      "window": "9:30-9:45",
      "veto_active": false,
      "active_vetoes": [],
      "preopen_count": 3,
      "max_preopen": 6,
      "preopen_active": [
        {
          "id": "no_pre_rth_news",
          "desc": "NO pre-RTH news scheduled (strongest factor)",
          "lift_pp": 21.1
        },
        {
          "id": "prior_day_mid",
          "desc": "Prior day close in middle 1/3 (no narrative)",
          "lift_pp": 9.5
        },
        {
          "id": "gap_large_down",
          "desc": "Gap < -100 pts",
          "lift_pp": 5.5
        }
      ],
      "post_pending": [
        {
          "id": "variant_no_fvg",
          "when": "signal",
          "desc": "FVGC variant is no_fvg (cleanest signal)",
          "lift_pp": 8.0
        }
      ],
      "projection": {
        "min_count": 3,
        "max_count": 4,
        "min_tier": {
          "action": "TAKE full size, BE@1R -> 3R fixed",
          "note": "~59% WR, PF 2.31, EV +0.54R (operating tier)"
        },
        "max_tier": {
          "action": "TAKE same size \u2014 do NOT scale up",
          "note": "4+ OOS too thin (n=1) to validate"
        },
        "locked": false
      },
      "expectancy": null,
      "extra_note": "8yr-validated (n=117): IS 59.8% / OOS 55.0% @ 3+, regime spread 9.4pp, year-floor 50%. Gap-down quiet bounce: when sellers gap it large-down without fresh catalyst, vol normal, prior close non-committal \u2014 fade the gap-down via no_fvg long in M1.",
      "notion_url": "https://www.notion.so/365e2f0e77608154b4caca8dcc0a7c70",
      "narrative": "<b>3/6 preopen factors confirmed</b> (no_pre_rth_news +21pp, prior_day_mid +9.5pp, gap_large_down +5.5pp) \u2014 already at the take tier, full size BE@1R \u2192 3R. Wait for the <b>no_fvg variant at signal time</b> (+8pp extra lift); thesis is gap-down fade with no catalyst and a non-committal prior close = sellers overextended."
    },
    {
      "name": "M2 Long",
      "direction": "long",
      "window": "9:45-10:00",
      "veto_active": false,
      "active_vetoes": [],
      "preopen_count": 1,
      "max_preopen": 4,
      "preopen_active": [
        {
          "id": "regime_bull",
          "desc": "60d NQ return > +5% (bull macro)",
          "lift_pp": 9.4
        }
      ],
      "post_pending": [
        {
          "id": "bull_930",
          "when": "9:31",
          "desc": "Bullish 9:30 1-min candle",
          "lift_pp": 20.6
        },
        {
          "id": "macro_1_2plus_fvgs",
          "when": "9:45",
          "desc": ">=2 FVGs printed in 9:30-9:45 macro",
          "lift_pp": 9.4
        },
        {
          "id": "has_5m_bear_fvg",
          "when": "9:35",
          "desc": "Bearish FVG in first 5min (counter-intuitive)",
          "lift_pp": 7.6
        }
      ],
      "projection": {
        "min_count": 1,
        "max_count": 4,
        "min_tier": {
          "action": "SKIP",
          "note": "3+ tier no longer viable on 8yr"
        },
        "max_tier": {
          "action": "TAKE Tier B size (capped), BE@1R -> 3R fixed",
          "note": "~64.5% WR, PF 2.62 \u2014 but regime-fragile"
        },
        "locked": false
      },
      "expectancy": {
        "tradeable_threshold": 3,
        "setup_pct_of_all_days": 31.3,
        "fire_rate_pct": 30.1,
        "ev_per_setup_day_R": 0.277,
        "fire_rate_now_pct": 29.6,
        "fire_rate_max_pct": 36.6
      },
      "extra_note": "TIER B / CONFIDENCE LOW. 8yr re-val: year-floor 26.7% (2021), 16.7% (2023). Trade 4+ tier ONLY, capped size. Stand aside in melt-up (NQ >+15% 60d AND VIX<15) or chop years. No robust replacement stack found in re-mining.",
      "notion_url": "https://www.notion.so/361e2f0e776081e69d5dfc696dbd5726",
      "narrative": "<b>Only 1/4 preopen active (regime_bull)</b> \u2014 needs a bullish 9:30 candle which runs counter to today's gap-down setup, making the 4-factor threshold structurally unlikely. Even if all 4 fire, <b>Tier B capped size only</b> \u2014 year-floor 16.7% in 2023 makes this the least reliable play in the matrix."
    },
    {
      "name": "M3 Long",
      "direction": "long",
      "window": "10:00-10:15",
      "veto_active": true,
      "active_vetoes": [
        {
          "id": "prior_day_mid",
          "desc": "Prior day close in middle 1/3 (no narrative)",
          "lift_pp": -15.4
        },
        {
          "id": "dow_tuesday",
          "desc": "Day is Tuesday",
          "lift_pp": -10.1
        }
      ],
      "preopen_count": 1,
      "max_preopen": 4,
      "preopen_active": [
        {
          "id": "not_fomc_week",
          "desc": "NOT FOMC week",
          "lift_pp": 7.4
        }
      ],
      "post_pending": [
        {
          "id": "no_5m_bull_fvg",
          "when": "9:35",
          "desc": "NO bullish FVG in first 5min (bulls not committed)",
          "lift_pp": 8.1
        },
        {
          "id": "has_5m_bear_fvg",
          "when": "9:35",
          "desc": "Bearish FVG in first 5min (seller liquidation)",
          "lift_pp": 6.8
        },
        {
          "id": "variant_no_fvg",
          "when": "signal",
          "desc": "FVGC variant is no_fvg (cleanest signal)",
          "lift_pp": 6.2
        }
      ],
      "projection": {
        "min_count": 1,
        "max_count": 4,
        "min_tier": {
          "action": "SKIP",
          "note": "no setup"
        },
        "max_tier": {
          "action": "TAKE same size \u2014 do NOT scale up",
          "note": "4+/5+ OOS collapses (\u0394 -17pp at 4+, -23pp at 5+)"
        },
        "locked": false
      },
      "expectancy": {
        "tradeable_threshold": 3,
        "setup_pct_of_all_days": 28.1,
        "fire_rate_pct": 31.8,
        "ev_per_setup_day_R": 0.087,
        "fire_rate_now_pct": 30.7,
        "fire_rate_max_pct": 30.1
      },
      "extra_note": "8yr-validated Tier A (n=264, 5/5 gates): IS 65.4% / OOS 61.6% @ 3+, year-floor 47.8%, regime spread 1.8pp \u2014 most regime-robust cell in the matrix. Thesis: Mon/Fri prior-weak no-bull-FVG mean-reversion. Magnet gate no longer required (8yr re-mine confirmed edge holds without it).",
      "notion_url": "https://www.notion.so/361e2f0e7760819bbbc7ca78b9faa8f9",
      "narrative": "<b>VETOED: prior_day_mid (\u221215pp) + Tuesday (\u221210pp) = \u221225pp combined drag</b> \u2014 mandatory skip regardless of session behavior. M3 Long's regime-robust edge applies Mon/Fri with a weak prior; neither condition holds today, so sit out entirely."
    }
  ],
  "avoid": {
    "factor_signals": [],
    "combo_signals": [
      {
        "status": "watch",
        "factors": [
          "overnight_down",
          "short_only",
          "tight_45min_or"
        ],
        "n": 31,
        "wr_pct": 22.6,
        "pf": 0.32,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "gap_down",
          "short_only",
          "tight_45min_or"
        ],
        "n": 44,
        "wr_pct": 25.0,
        "pf": 0.36,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "gap_down",
          "macro_w1",
          "tight_45min_or"
        ],
        "n": 35,
        "wr_pct": 25.7,
        "pf": 0.4,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "long_only",
          "macro_w1",
          "tight_45min_or"
        ],
        "n": 57,
        "wr_pct": 26.3,
        "pf": 0.35,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "bullish_930",
          "overnight_down",
          "tight_45min_or"
        ],
        "n": 45,
        "wr_pct": 26.7,
        "pf": 0.33,
        "post_needed": [
          {
            "factor": "bullish_930",
            "desc": "9:30 candle closed bullish"
          },
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "bearish_930",
          "gap_down",
          "tight_45min_or"
        ],
        "n": 46,
        "wr_pct": 28.3,
        "pf": 0.43,
        "post_needed": [
          {
            "factor": "bearish_930",
            "desc": "9:30 candle closed bearish"
          },
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      }
    ],
    "narrative": "<b>Tight 45-min OR is the universal kill switch</b> \u2014 if the OR lands in the bottom 20% by 10:15, every short combo collapses to 22\u201328% WR (PF &lt;0.45). With gap-down + overnight-down already stacked, a tight OR signals structural exhaustion; full stand-down required, no fading into a narrow range day."
  },
  "active_plays": [
    {
      "name": "M1 Short \u2014 Confluence Model (8yr re-validated)",
      "direction": "short",
      "status": "verified",
      "wr_base": "51.2% (no filter post-veto), 60.6% (at 2+ confluences)",
      "sample_size": 246,
      "action_plan": "See Notion Morning Routine for the complete timeline. Quick version: vetoes off + FVGC short fires 9:30-9:45 \u2192 SL-adaptive TP + bias x 9:30-FVG sizing matrix + NO BE move + don't touch.",
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M1 Long \u2014 Confluence Model (NEW 8yr)",
      "direction": "long",
      "status": "verified",
      "wr_base": null,
      "sample_size": 117,
      "action_plan": null,
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M2 Long \u2014 Confluence Model (8yr DOWNGRADED Tier B)",
      "direction": "long",
      "status": "verified",
      "wr_base": null,
      "sample_size": 110,
      "action_plan": null,
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M3 Long \u2014 Confluence Model (8yr re-validated)",
      "direction": "long",
      "status": "verified",
      "wr_base": null,
      "sample_size": 264,
      "action_plan": null,
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "W1 Short \u2014 Post-Sweep Continuation",
      "direction": "short",
      "status": "under_review",
      "wr_base": null,
      "sample_size": null,
      "action_plan": "1) Confirm W1 short trigger (FVGC short 9:30-9:45). 2) Pull up 15m chart, identify nearest unswept bullish 15m FVG below current price. 3) Has price touched it between 9:30 and now? If YES \u2192 take with full size + extended target. If NO \u2192 fall back to standard W1 confluence model. 4) BE@1R then ride for 3R+, aggressive trail for 5R+.",
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "FVGC Off of 930 Candle (9:30 Candle FVG Premium Sub-Tier)",
      "direction": "short",
      "status": "verified",
      "wr_base": "66.7%",
      "sample_size": 33,
      "action_plan": "When FVGC short signal fires in 9:30-9:45, look at the FVG's creation timestamp. If between 9:29:30 and 9:31:00 \u2192 premium sub-tier, size up. Otherwise standard M1 Short sizing.",
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "No News + Macro 1 Short",
      "direction": "short",
      "status": "idea",
      "wr_base": "60.0%",
      "sample_size": 185,
      "action_plan": "Check economic calendar. If clean day (no red folder), shorts in macro 1 have a structural edge. Combine with wide OR for 75% WR.",
      "pre_met": [
        "no_red_folder"
      ],
      "pre_missing": [],
      "match_status": "active"
    },
    {
      "name": "FVGC To Opening Range H/L",
      "direction": "both",
      "status": "backtesting",
      "wr_base": "61.7%",
      "sample_size": 60,
      "action_plan": "At 9:45: note OR high and OR low. Check OR close bias (top 40% = short toward OR_L, bottom 40% = long toward OR_H, middle = skip). Take FVGC entries where R-to-OR < 1.0 and neither OR side has been swept. Hold original SL, target 1R. Play is dead once any OR level is breached.",
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "Reversal-Confirmed FVG Continuation (HTF 15m Sweep)",
      "direction": "both",
      "status": "backtesting",
      "wr_base": "68.0%",
      "sample_size": 100,
      "action_plan": "Identify unmitigated 15m FVGs pre-market. If one gets swept (non-reclaiming) and an opposing FVG inverts, take the FVGC reversal signal.",
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "15m FVG Breakout Continuation",
      "direction": "both",
      "status": "rejected",
      "wr_base": "31.9% (re-run actual)",
      "sample_size": 47,
      "action_plan": "DO NOT TRADE. Pending further investigation if any salvage path is found.",
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "W3 Long \u2014 Confluence Model",
      "direction": "long",
      "status": "backtesting",
      "wr_base": "53.8%",
      "sample_size": 238,
      "action_plan": "Pre-10am: identify unswept 15m and 1H FVGs above current price. Note distances in R-multiples (pts / expected SL). At 10:00+: if a long FVGC entry forms (not BOS), check tier. A+ (15m FVG \u22643R): set TP at the 15m FVG price, avg ~1.9R. A (both 15m + 1H ahead): target 1.5\u20132R. B (one draw): target 1R. C (no draw): skip.",
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    }
  ],
  "partial_plays": [],
  "game_plan": {
    "one_liners": [],
    "checklist": [
      "9:30 candle direction \u2014 bearish confirms most high-edge combos",
      "Watch 45-min OR width by 10:15 \u2014 WIDE = green light, TIGHT = stand down"
    ],
    "best_targets": [
      {
        "label": "London low",
        "price": 28836.0,
        "distance_pts": -27.0,
        "direction": "below"
      },
      {
        "label": "Overnight low",
        "price": 28831.0,
        "distance_pts": -32.0,
        "direction": "below"
      },
      {
        "label": "15m FVG (bearish)",
        "price": 28879.5,
        "distance_pts": 16.5,
        "direction": "above"
      },
      {
        "label": "Asia low",
        "price": 28885.0,
        "distance_pts": 22.0,
        "direction": "above"
      }
    ],
    "narrative": "<b>Primary: M1 Short</b> if 9:30 candle is bearish with large body \u2192 runner mode, TP@5R no-BE, PDL 28814.75 as guide; <b>Alt: M1 Long</b> \u2014 3 preopen factors stacked, take full size BE@1R \u2192 3R on no_fvg variant; <b>Kill switch: tight 45-min OR by 10:15</b> \u2192 stand down all shorts entirely."
  }
};
