// Auto-generated by tools/morning_briefing.py --export-dashboard.
// Edit tools/briefing/briefing.json (e.g. to add narratives) then
// rerun the briefing or use --rewrite-js-from-json.
window.BRIEFING_DATA = {
  "schema_version": 1,
  "meta": {
    "date": "2026-05-21",
    "day_of_week": "Thursday",
    "generated_at_et": "2026-05-21T09:35:17.088499-04:00",
    "generated_at_pt": "2026-05-21T06:35:17.088499-07:00",
    "mode": "live"
  },
  "freshness": [],
  "or_forecast": {
    "available": false,
    "narrative": "Today\u2019s OR-width forecast and sizing tier data aren\u2019t available yet. With <b>no forecast points</b> and <b>no sizing tier</b> defined, expect execution to rely on standard pre-market levels and your existing risk settings until new inputs load. Monitor for updates this morning to adjust order sizing and potential stop placement once the OR-width forecast and tier are provided.",
    "stepwise": null
  },
  "calendar": {
    "day_of_week": "Thursday",
    "dow_note": "Thursday is the STRONGEST day in the sample (WR ~55.8%). Volume Profile play: if entry is inside prior day's Value Area (VAL-VAH), 73.7% WR / 2.89 PF. Pull up prior day VP and note the levels.",
    "unknown": false,
    "is_fomc_week": false,
    "events": [
      {
        "event": "Philly Fed Manufacturing Index",
        "time_et": "12:30",
        "impact": "Medium",
        "currency": ""
      },
      {
        "event": "Unemployment Claims",
        "time_et": "12:30",
        "impact": "Medium",
        "currency": ""
      },
      {
        "event": "Flash Manufacturing PMI",
        "time_et": "13:45",
        "impact": "Medium",
        "currency": ""
      },
      {
        "event": "Flash Services PMI",
        "time_et": "13:45",
        "impact": "Medium",
        "currency": ""
      }
    ],
    "narrative": "Today is a Thursday with historically strong intraday activity, so expect amplified moves if price interacts with yesterday\u2019s value area; prioritize trades that trigger inside prior day\u2019s VAL-VAH to leverage the <b>73.7% WR</b> and ~<b>2.89 PF</b> potential, while keeping an eye on the prior day VP levels. The economic calendar features <b>Philly Fed Manufacturing Index</b> and <b>Unemployment Claims</b> at 12:30 ET, with <b>Flash Manufacturing PMI</b> and <b>Flash Services PMI</b> at 13:45 ET, each with <b>Medium</b> impact\u2014expect tighter price action around these releases and use smaller sizing if volatility spikes. This is not FOMC week, so no specific FOMC-driven risk drift is expected, but be prepared for standard Thursday-volume amplification around data prints."
  },
  "pre_open": {
    "current_price": 29194.25,
    "current_price_ts": "09:25 ET",
    "prior_rth": {
      "close": 29396.0,
      "open": 29073.75,
      "high": 29396.75,
      "low": 29008.5,
      "close_position": 0.9980682549903412,
      "label": "prior_day_up"
    },
    "overnight": {
      "high": 29464.5,
      "low": 29113.0,
      "range": 351.5,
      "direction": "down",
      "tight": false,
      "wide": false
    },
    "asia": {
      "high": 29439.75,
      "low": 29164.0
    },
    "london": {
      "high": 29464.5,
      "low": 29192.25
    },
    "gap": {
      "pts": -201.75,
      "pct": -0.6863178663763778,
      "direction": "gap_down"
    },
    "data_notes": [],
    "narrative": "This morning the market is trading below yesterday\u2019s RTH close, with a <b>gap down</b> of <b>-201.75 pts</b> or about <b>-0.69%</b> open, signaling selling pressure into the pre-market. The <b>overnight range</b> spanned <b>29113.0\u201329464.5</b>, placing current price at <b>29194.25</b> and just inside the lower half of that range, suggesting the opening could lean toward a firmer bid if early support holds; otherwise expect continued volatility as the day session attempts to rediscover value near yesterday\u2019s <b>open</b> around <b>29073.75</b> and <b>high</b> near <b>29396.75</b>. Consider tighter risk controls and be prepared for quick re-entries as price tests key levels near yesterday\u2019s <b>low</b> 29008.5 and <b>high</b> 29396.75."
  },
  "levels": {
    "scope_pts": 100,
    "above": [
      {
        "group": "htf_fvg_1H",
        "label": "1H FVG (bearish)",
        "price": 29293.75,
        "distance_pts": 99.5,
        "direction": "above",
        "tier": "A",
        "hit_rate_45m_pct": 22.5,
        "wr_as_magnet_pct": 64.2,
        "pf_as_magnet": 2.16,
        "below_baseline": false
      }
    ],
    "below": [
      {
        "group": "london",
        "label": "London low",
        "price": 29192.25,
        "distance_pts": -2.0,
        "direction": "below",
        "tier": "C",
        "hit_rate_45m_pct": 54.3,
        "wr_as_magnet_pct": 47.4,
        "pf_as_magnet": 0.95,
        "below_baseline": true
      },
      {
        "group": "asia",
        "label": "Asia low",
        "price": 29164.0,
        "distance_pts": -30.25,
        "direction": "below",
        "tier": "A",
        "hit_rate_45m_pct": 59.2,
        "wr_as_magnet_pct": 54.2,
        "pf_as_magnet": 1.22,
        "below_baseline": false
      },
      {
        "group": "overnight",
        "label": "Overnight low",
        "price": 29113.0,
        "distance_pts": -81.25,
        "direction": "below",
        "tier": "C",
        "hit_rate_45m_pct": 41.1,
        "wr_as_magnet_pct": 48.7,
        "pf_as_magnet": 0.86,
        "below_baseline": true
      }
    ],
    "narrative": "Today's near-term liquidity sits with <b>London low</b> at <b>29192.25</b> (about <b>2.0 points below</b> the current price) and <b>Overnight low</b> at <b>29113.0</b> (about <b>81.25 points below</b>). A notable resistance above is the <b>1H FVG (bearish)</b> at <b>29293.75</b>, roughly <b>99.5 points above</b> current, suggesting potential selling pressure if price moves up to that level. Overall, expect liquidity clustering below current price with risk of continued downside bias toward the <b>Asia low</b> at <b>29164.0</b>, about <b>30.25 points</b> away, unless price quickly reverses."
  },
  "factors": {
    "active": [
      "gap_down",
      "no_pre_rth_news",
      "no_red_folder",
      "not_fomc_week",
      "overnight_down",
      "prior_day_up",
      "thursday"
    ],
    "inactive": [
      "elevated_vixy",
      "entry_inside_prior_day_value_area",
      "friday",
      "gap_up",
      "has_pre_rth_news",
      "has_red_folder",
      "is_fomc_week",
      "low_vixy",
      "monday",
      "normal_vixy",
      "overnight_up",
      "prior_day_down",
      "tight_overnight",
      "tuesday",
      "wednesday",
      "wide_overnight"
    ],
    "unknown": [],
    "narrative": "Today is a <b>gap-down</b> morning with <b>overnight_down</b> pressure already in the books and <b>no_pre_rth_news</b> driving returns. With <b>prior_day_up</b> and <b>thursday</b> as active factors, expect continued cautious pre-market action into regular session, as the market may test yesterday\u2019s lower levels. Since we\u2019re not in <b>fomc_week</b> and there\u2019s <b>no_red_folder</b>, risk is more aligned to price structure than surprise catalysts, so honor tighter risk checks and look for clean, low-variance entries if you see a defined early reversion or continuation setup."
  },
  "armed_edges": [],
  "watch_list": [
    {
      "stars": "\u2605\u2605\u2605",
      "factors": [
        "macro_w1",
        "no_red_folder",
        "wide_45min_or"
      ],
      "n": 64,
      "wr_pct": 75.0,
      "pf": 3.21,
      "p_wr": 0.0,
      "pre_matched": [
        "no_red_folder"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "no_pre_rth_news",
        "wide_45min_or"
      ],
      "n": 67,
      "wr_pct": 74.6,
      "pf": 3.27,
      "p_wr": 0.0,
      "pre_matched": [
        "no_pre_rth_news"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "short_only",
        "wide_45min_or"
      ],
      "n": 51,
      "wr_pct": 74.5,
      "pf": 3.07,
      "p_wr": 0.0,
      "pre_matched": [],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "wide_45min_or"
      ],
      "n": 77,
      "wr_pct": 72.7,
      "pf": 2.84,
      "p_wr": 0.0,
      "pre_matched": [],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "macro_w1",
        "not_fomc_week",
        "wide_45min_or"
      ],
      "n": 67,
      "wr_pct": 70.1,
      "pf": 2.47,
      "p_wr": 0.001,
      "pre_matched": [
        "not_fomc_week"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "bearish_930",
        "macro_w1",
        "overnight_down"
      ],
      "n": 64,
      "wr_pct": 68.8,
      "pf": 2.3,
      "p_wr": 0.003,
      "pre_matched": [
        "overnight_down"
      ],
      "post_needed": [
        {
          "factor": "bearish_930",
          "desc": "9:30 candle closed bearish"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "gap_down",
        "short_only",
        "wide_45min_or"
      ],
      "n": 92,
      "wr_pct": 67.4,
      "pf": 2.18,
      "p_wr": 0.0,
      "pre_matched": [
        "gap_down"
      ],
      "post_needed": [
        {
          "factor": "wide_45min_or",
          "desc": "45-min OR (9:30\u201310:15) in top 20% \u2014 KEY confirmation"
        }
      ]
    },
    {
      "stars": "\u2605\u2605",
      "factors": [
        "bullish_930",
        "long_only",
        "macro_w2"
      ],
      "n": 135,
      "wr_pct": 66.7,
      "pf": 1.63,
      "p_wr": 0.0,
      "pre_matched": [],
      "post_needed": [
        {
          "factor": "bullish_930",
          "desc": "9:30 candle closed bullish"
        }
      ]
    }
  ],
  "w1_short_confluence": {
    "preopen_count": 3,
    "active_factors": [
      "gap_down",
      "large_gap",
      "overnight_down"
    ],
    "tier": null
  },
  "matrix_plays": [
    {
      "name": "M1 Short",
      "direction": "short",
      "window": "9:30-9:45",
      "timeframe": "30s",
      "veto_active": false,
      "active_vetoes": [],
      "preopen_count": 1,
      "max_preopen": 5,
      "preopen_active": [
        {
          "id": "gap_large_down",
          "desc": "Gap < -100 pts",
          "lift_pp": 19.0
        }
      ],
      "post_pending": [
        {
          "id": "bear_930",
          "when": "9:31",
          "desc": "Bearish 9:30 1-min candle",
          "lift_pp": 21.3
        },
        {
          "id": "c930_body_top_q",
          "when": "9:31",
          "desc": "9:30 candle body in top quartile (>=23 pts)",
          "lift_pp": 15.6
        }
      ],
      "projection": {
        "min_count": 1,
        "max_count": 3,
        "min_tier": {
          "action": "SKIP",
          "note": "no edge"
        },
        "max_tier": {
          "action": "TAKE full size, runner mode",
          "note": "~73% WR, PF 2.71"
        },
        "locked": false
      },
      "expectancy": {
        "tradeable_threshold": 2,
        "setup_pct_of_all_days": 36.0,
        "fire_rate_pct": 23.0,
        "ev_per_setup_day_R": 0.253,
        "fire_rate_now_pct": 21.1,
        "fire_rate_max_pct": 20.2
      },
      "extra_note": "RUNNER EXIT DOCTRINE: TP@5R no-BE is the optimal exit (PF 3+). BE management caps the edge. Do not apply M2/M3 long-style BE@1R here.",
      "notion_url": "https://www.notion.so/33de2f0e776081889879c4dcbd495996",
      "narrative": "For today\u2019s pre-market M1 Short window (9:30\u20139:45, 30s cadence), the setup is active with a <b>gap_large_down</b> preopen flag and a projected edge to take on a full-size, runner-mode exit near <b>73% WR</b> with a <b>PF 2.71</b> expectation, provided you ride the bear signal through the open. Anticipate immediate post-open moves: a <b>bear_930</b> cue at 9:31 with ~<b>21.3 pts</b> lift potential, and a secondary cue if the 9:30 candle sits in the top quartile (\u2248<b>23 pts</b> body) at 9:31, offering about <b>15.6 pts</b> of edge. Given the <b>RUNNER EXIT DOCTRINE</b>, target a take-profit at 5R with strict BE-free management, and avoid M2/M3 BE angles for this session."
    },
    {
      "name": "M1 Long",
      "direction": "long",
      "window": "9:30-9:45",
      "timeframe": "30s",
      "veto_active": false,
      "active_vetoes": [],
      "preopen_count": 2,
      "max_preopen": 6,
      "preopen_active": [
        {
          "id": "no_pre_rth_news",
          "desc": "NO pre-RTH news scheduled (strongest factor)",
          "lift_pp": 21.1
        },
        {
          "id": "gap_large_down",
          "desc": "Gap < -100 pts",
          "lift_pp": 5.5
        }
      ],
      "post_pending": [
        {
          "id": "variant_no_fvg",
          "when": "signal",
          "desc": "FVGC variant is no_fvg (cleanest signal)",
          "lift_pp": 8.0
        }
      ],
      "projection": {
        "min_count": 2,
        "max_count": 3,
        "min_tier": {
          "action": "SKIP",
          "note": "no setup"
        },
        "max_tier": {
          "action": "TAKE full size, BE@1R -> 3R fixed",
          "note": "~59% WR, PF 2.31, EV +0.54R (operating tier)"
        },
        "locked": false
      },
      "expectancy": null,
      "extra_note": "8yr-validated (n=117): IS 59.8% / OOS 55.0% @ 3+, regime spread 9.4pp, year-floor 50%. Gap-down quiet bounce: when sellers gap it large-down without fresh catalyst, vol normal, prior close non-committal \u2014 fade the gap-down via no_fvg long in M1.",
      "notion_url": "https://www.notion.so/365e2f0e77608154b4caca8dcc0a7c70",
      "narrative": "Today\u2019s M1 Long setup targets the 9:30\u20139:45 window with a focus on a clean signal and limited preopen noise. With <b>preopen</b> signals counting up to <b>2</b> (out of a possible <b>6</b>) and the strongest factor being \u201cNo pre-RTH news\u201d (lift_pp <b>21.1</b>), the plan leans toward taking <b>full size</b> if the signal confirms, aiming for <b>BE@1R \u2192 3R</b> trades when the max tier conditions are met (roughly a <b>59%</b> WR and <b>EV +0.54R</b>). If the variant is no_fvg at signal, anticipate a favorable lift of <b>8.0</b> in post-pending timing, but otherwise manage risk with the current <b>9:30\u20139:45</b> cadence and a skip if no setup is present."
    },
    {
      "name": "M2 Long",
      "direction": "long",
      "window": "9:45-10:00",
      "timeframe": "30s",
      "veto_active": false,
      "active_vetoes": [],
      "preopen_count": 1,
      "max_preopen": 4,
      "preopen_active": [
        {
          "id": "dow_thursday",
          "desc": "Day is Thursday",
          "lift_pp": 10.0
        }
      ],
      "post_pending": [
        {
          "id": "bull_930",
          "when": "9:31",
          "desc": "Bullish 9:30 1-min candle",
          "lift_pp": 20.6
        },
        {
          "id": "macro_1_2plus_fvgs",
          "when": "9:45",
          "desc": ">=2 FVGs printed in 9:30-9:45 macro",
          "lift_pp": 9.4
        },
        {
          "id": "has_5m_bear_fvg",
          "when": "9:35",
          "desc": "Bearish FVG in first 5min (counter-intuitive)",
          "lift_pp": 7.6
        }
      ],
      "projection": {
        "min_count": 1,
        "max_count": 4,
        "min_tier": {
          "action": "SKIP",
          "note": "3+ tier no longer viable on 8yr"
        },
        "max_tier": {
          "action": "TAKE Tier B size (capped), BE@1R -> 3R fixed",
          "note": "~64.5% WR, PF 2.62 \u2014 but regime-fragile"
        },
        "locked": false
      },
      "expectancy": {
        "tradeable_threshold": 3,
        "setup_pct_of_all_days": 31.3,
        "fire_rate_pct": 30.1,
        "ev_per_setup_day_R": 0.277,
        "fire_rate_now_pct": 29.6,
        "fire_rate_max_pct": 36.6
      },
      "extra_note": "TIER B / CONFIDENCE LOW. 8yr re-val: year-floor 26.7% (2021), 16.7% (2023). Trade 4+ tier ONLY, capped size. Stand aside in melt-up (NQ >+15% 60d AND VIX<15) or chop years. No robust replacement stack found in re-mining.",
      "notion_url": "https://www.notion.so/361e2f0e776081e69d5dfc696dbd5726",
      "narrative": "Today, the M2 Long window from <b>9:45\u201310:00</b> is active with a <b>long</b> orientation and a limited <b>30s</b> cadence, but the setup is considered <b>TIER B / CONFIDENCE LOW</b> and should only trade with <b>4+ tier</b> size cap and <b>capped</b> risk. The post-event signals favoring execution are Fed by a <b>bullish 9:30 1-min candle</b> (lift <b>+20.6</b>), plus potential <b>>=2 FVGs</b> printed in 9:30\u20139:45 (lift <b>+9.4</b>) and a counter-intuitive <b>bearish 5m FVG</b> signal (lift <b>+7.6</b>), but with regime fragility\u2014consider standing aside if melt-up conditions occur (NQ >+15% 60d and VIX <15). Execute only if you accept the <b>min 1 / max 4</b> count constraint, and favor taking the <b>Tier B fixed</b> size target around the 1R\u20133R level if the setup fires."
    },
    {
      "name": "M3 Long",
      "direction": "long",
      "window": "10:00-10:15",
      "timeframe": "30s",
      "veto_active": false,
      "active_vetoes": [],
      "preopen_count": 1,
      "max_preopen": 4,
      "preopen_active": [
        {
          "id": "not_fomc_week",
          "desc": "NOT FOMC week",
          "lift_pp": 7.4
        }
      ],
      "post_pending": [
        {
          "id": "no_5m_bull_fvg",
          "when": "9:35",
          "desc": "NO bullish FVG in first 5min (bulls not committed)",
          "lift_pp": 8.1
        },
        {
          "id": "has_5m_bear_fvg",
          "when": "9:35",
          "desc": "Bearish FVG in first 5min (seller liquidation)",
          "lift_pp": 6.8
        },
        {
          "id": "variant_no_fvg",
          "when": "signal",
          "desc": "FVGC variant is no_fvg (cleanest signal)",
          "lift_pp": 6.2
        }
      ],
      "projection": {
        "min_count": 1,
        "max_count": 4,
        "min_tier": {
          "action": "SKIP",
          "note": "no setup"
        },
        "max_tier": {
          "action": "TAKE same size \u2014 do NOT scale up",
          "note": "4+/5+ OOS collapses (\u0394 -17pp at 4+, -23pp at 5+)"
        },
        "locked": false
      },
      "expectancy": {
        "tradeable_threshold": 3,
        "setup_pct_of_all_days": 28.1,
        "fire_rate_pct": 31.8,
        "ev_per_setup_day_R": 0.087,
        "fire_rate_now_pct": 30.7,
        "fire_rate_max_pct": 30.1
      },
      "extra_note": "8yr-validated Tier A (n=264, 5/5 gates): IS 65.4% / OOS 61.6% @ 3+, year-floor 47.8%, regime spread 1.8pp \u2014 most regime-robust cell in the matrix. Thesis: Mon/Fri prior-weak no-bull-FVG mean-reversion. Magnet gate no longer required (8yr re-mine confirmed edge holds without it).",
      "notion_url": "https://www.notion.so/361e2f0e7760819bbbc7ca78b9faa8f9",
      "narrative": "Today\u2019s M3 Long setup for 10:00\u201310:15 on a 30-second window signals a favorable long edge with <b>1\u20134</b> projected entries and a cap to <b>4+/5+</b> OOS activity\u2014the system remains <b>not vetoed</b> and currently <b>preopen_active</b> with a lift to <b>7.4</b>. Expect a clean signal when the post-open context aligns with the <b>FVGC variant no_fvg</b> or the first-5-minute FVG print, where the two post-pending signals carry lifts of <b>8.1</b> and <b>6.8</b> respectively; if a bullish FVG fails to appear in the first 5 minutes, the <b>no_5m_bull_fvg</b> path is favored. Trade entries, if triggered, should be taken at the same size with no scaling beyond the current size, as the projection notes caution against escalations beyond 4\u20135+ OOS."
    }
  ],
  "avoid": {
    "factor_signals": [
      {
        "factor": "prior_day_up",
        "wr_pct": 48.8,
        "lift_pp": -2.9,
        "pf": 0.99,
        "p_wr": 0.0647
      }
    ],
    "combo_signals": [
      {
        "status": "watch",
        "factors": [
          "overnight_down",
          "short_only",
          "tight_45min_or"
        ],
        "n": 31,
        "wr_pct": 22.6,
        "pf": 0.32,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "macro_w1",
          "prior_day_up",
          "tight_45min_or"
        ],
        "n": 47,
        "wr_pct": 23.4,
        "pf": 0.33,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "gap_down",
          "short_only",
          "tight_45min_or"
        ],
        "n": 44,
        "wr_pct": 25.0,
        "pf": 0.36,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "gap_down",
          "macro_w1",
          "tight_45min_or"
        ],
        "n": 35,
        "wr_pct": 25.7,
        "pf": 0.4,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "long_only",
          "macro_w1",
          "tight_45min_or"
        ],
        "n": 57,
        "wr_pct": 26.3,
        "pf": 0.35,
        "post_needed": [
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      },
      {
        "status": "watch",
        "factors": [
          "bullish_930",
          "overnight_down",
          "tight_45min_or"
        ],
        "n": 45,
        "wr_pct": 26.7,
        "pf": 0.33,
        "post_needed": [
          {
            "factor": "bullish_930",
            "desc": "9:30 candle closed bullish"
          },
          {
            "factor": "tight_45min_or",
            "desc": "45-min OR in bottom 20% \u2014 HARD stand-down signal"
          }
        ]
      }
    ],
    "narrative": "Today\u2019s signals show a cautious posture: overall factor signals are mixed with <b>prior_day_up</b> near-neutral odds (<b>pf 0.99</b>, <b>wr_pct 48.8</b> but <b>lift_pp -2.9</b>), and multiple combo signals are in <b>watch</b> with a shared HARD stand-down threshold on the <b>45-min OR</b> signal, specifically in the <b>bottom 20%</b>. Expect potential soft topside participation and ready to stand down if the <b>tight_45min_or</b> condition triggers; avoid aggressive longs unless we see a bullish 9:30 close or a clear reversion above the <b>45-min OR bottom-20%</b> zone. In practice, favor tight stops and readiness to reduce risk on any break below the <b>tight_45min_or</b> line."
  },
  "active_plays": [
    {
      "name": "VP Magnet Play (A+) \u2014 n_vp\u22652 + VA-Edge",
      "direction": "both",
      "status": "backtesting",
      "wr_base": "83% at +3R (81% OOS); 9/9 yrs positive; multi-TF (30s+1m+2m+3m)",
      "sample_size": 208,
      "action_plan": "Watch 30s + 1m + 2m + 3m simultaneously 9:30-10:15 ET. On EVERY FVGC fire from ANY TF: 1) variant must be bos, ifvg, or no_fvg (NOT PS); 2) n_vp_targets >= 2 (POC/VAH/VAL in trade direction within 0.5R-3R); 3) direction-matched VA-edge ahead (VAL for long, VAH for short within 0.5-3R); 4) within 9:30-10:15 window. All YES from ANY TF -> take at 1.5x size, stop -1R, fixed TP +3R, no BE. SUBSEQUENT same-day same-direction fires on slower TFs are re-confirmations only -- already in trade, no action. Median gap between first and second fire when multi-TF triggers same direction: 2.5 min, 65% within 5 min.\n\nExit Strategy: Stop \u22121R (FVG geometry). Fixed TP +3R. NO BE move (BE clips runners \u2014 see RM section). Max consecutive losers in 9yr sample: 2. Max yearly DD: \u22122R.",
      "notion_url": "https://www.notion.so/VP-Magnet-Play-A-n_vp-2-VA-Edge-367e2f0e7760811aa7b0efd3aff8024e",
      "description": null,
      "pre_market_conditions": "Compute prior-RTH (9:30-16:00 ET previous session) POC, VAH, VAL from 30s NQ candles (1.0 pt buckets, 70% value area). Levels are KNOWN by 4:00pm ET the prior day. By 9:30 you should have a printout: POC=, VAH=, VAL=__, and where current price sits relative to them.",
      "tier": "A",
      "confidence": "high",
      "frequency": "~23/year (~2/month) under multi-TF rule. Median gap between setups: 9 trading days. p95 gap: 49 days. Max gap (9yr sample): 95 days (~4.5 months).",
      "pf_base": 13.41,
      "avg_mfe_r": 4.63,
      "window": [
        "9:30-9:45",
        "9:45-10:00",
        "10:00-10:15"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M1 Long \u2014 Confluence Model",
      "direction": "long",
      "status": "verified",
      "wr_base": "59.8% IS / 55.0% OOS @ 3+ (8yr-validated)",
      "sample_size": 117,
      "action_plan": "At 9:31 check 9:30 candle body \u2014 if top quartile, skip (veto, c930_body_top_q -5.5pp). At signal fire (9:30-9:45), require variant_no_fvg for cleanest setup (+8.0pp). Total 3+ confluences \u2192 take full size with BE@1R \u2192 TP@3R. Do not scale up at 4+ tier (OOS n=1).\n\nExit Strategy: BE@1R \u2192 3R fixed target. EV +0.54R/trade, PF 2.31. Standard size at 3+ tier (do NOT scale up at 4+ \u2014 n thin OOS).",
      "notion_url": "https://www.notion.so/M1-Long-Confluence-Model-365e2f0e77608154b4caca8dcc0a7c70",
      "description": "NEW play (2026-05-18) discovered via multi_cell_8yr_v2 re-mining on 8yr data. Gap-down quiet morning bounce: long FVGC 9:30-9:45 when overnight gap-down + no pre-RTH news + vixy_normal + variant_no_fvg + calendar factors align. 7-pro / 2-veto stack passes all 5 acceptance gates (year-floor 50%, regime spread 9.4pp, IS/OOS delta 4.8pp, n=117 over 8yr). The bullish counterpart to M1 Short \u2014 same window, opposite setup logic (fade gap-down vs continuation on gap-down panic).",
      "pre_market_conditions": "Hard vetoes (skip entirely): prior day closed bottom 1/3 (prior_day_weak). Pre-market confluences (check by 9:25): no pre-RTH news scheduled (+21.1pp), prior day closed in middle 1/3 (33-67%, +9.5pp), VIXY in normal regime (+6.6pp), IS FOMC week (+6.3pp), day=Wednesday (+6.3pp), gap < -100 pts (gap_large_down, +5.5pp). NOT FOMC week is NOT a confluence here \u2014 the play wants FOMC-week Wednesdays.",
      "tier": "A",
      "confidence": "medium",
      "frequency": "~14/yr (~1.2/mo) \u2014 roughly 1 every 25 days. From 8yr backtest, 117 trades.",
      "pf_base": 2.31,
      "avg_mfe_r": 2.5,
      "window": [
        "9:30-9:45"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M3 Long \u2014 Confluence Model",
      "direction": "long",
      "status": "verified",
      "wr_base": "65.4% IS / 61.6% OOS @ 3+ (8yr re-validated)",
      "sample_size": 264,
      "action_plan": "By 10:00 score these intraday factors: NO bullish FVG in first 5min (no_5m_bull_fvg) \u2014 counter-intuitive but signals the bulls haven't shown; bearish FVG in first 5min (has_5m_bear_fvg) \u2014 seller liquidation creates fade opp; variant_no_fvg signal (engine flag at trigger). Vetoes: opex week, day=Tuesday. Take FVGC long signal 10:00-10:15 at 3+ confluence, full size; do NOT add size at 4+/5+ tier (OOS-collapses).\n\nExit Strategy: BE@1R \u2192 2R fixed target. EV +0.45R/trade, PF 2.26. Standard size at 3+ tier (do NOT scale up at 4+ \u2014 collapses OOS).",
      "notion_url": "https://www.notion.so/M3-Long-Confluence-Model-361e2f0e7760819bbbc7ca78b9faa8f9",
      "description": "Long FVGC 10:00-10:15 \u2014 Monday/Friday prior-weak no-bull-FVG mean-reversion play. 7 confluences + 3 vetoes. 8yr re-validated (2018-2026, n=264): WR 65.4% IS / 61.6% OOS, year-floor 47.8%, regime spread 1.8pp across bull/bear/neutral. Was Tier B; upgraded to Tier A based on multi_cell_8yr_v2 study (2026-05-18) which showed the OLD compression-thesis stack misidentified the play \u2014 true edge is calendar (Mon/Fri) + prior_day_weak + variant_no_fvg.",
      "pre_market_conditions": "Hard vetoes (skip entirely): opex week OR day=Tuesday OR prior_day closed in middle 1/3 (33-67% of range). Pre-market confluences: day=Monday OR day=Friday (calendar lift), prior_day_weak (closed bottom 1/3), NOT FOMC week. By 9:35 add intraday confluences.",
      "tier": "A",
      "confidence": "medium",
      "frequency": "~2.66 trades/month at 3+ confluence (after vetoes)",
      "pf_base": 2.26,
      "avg_mfe_r": 2,
      "window": [
        "10:00-10:15"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M2 Long \u2014 Confluence Model",
      "direction": "long",
      "status": "backtesting",
      "wr_base": "64.5% 8yr @ 4+ tier / REGIME-FRAGILE (2021=36%, 2023=17%)",
      "sample_size": 110,
      "action_plan": "At 9:31 check bull_930. At 9:35 check first-5min bear FVG presence. At 9:45 confirm \u22652 FVGs printed in 9:30-9:45 macro. Then FVGC long fires 9:45-10:00 (BOS, IFVG, no_fvg \u2014 never protected_swing). Count 7 confluences total, take 3+.\n\nExit Strategy: 4+ TIER ONLY. BE@1R \u2192 3R fixed (+0.57R EV, PF 2.62 on 8yr). Cap size at Tier B. Hard stand-aside on 2021/2023 regime types (grind-higher melt-up / VIX-elevated chop).",
      "notion_url": "https://www.notion.so/M2-Long-Confluence-Model-361e2f0e776081e69d5dfc696dbd5726",
      "description": "DOWNGRADED 2026-05-18 from Tier A. The 8yr re-validation (multi_cell_8yr_v2) revealed the original 30-month OOS sample (n=20) masked severe regime fragility: 2021 WR collapsed to 26.7%, 2023 to 16.7% at 4+ tier. Old factor stack does NOT generalize back to 2018-2022. Re-mining on 8yr couldn't find a robust replacement stack (best new stack only n=14 trades). Trade 4+ tier only at capped size; expect regime-driven drawdowns; consider standing aside in melt-up / VIX-elevated regimes.",
      "pre_market_conditions": "Hard vetoes: opex week OR Wednesday OR 60d NQ return < -5% \u2192 skip entirely. Pre-market confluences: gap up >10pts, regime_bull (60d NQ > +5%), pre-RTH news on calendar, day=Thursday.",
      "tier": "B",
      "confidence": "low",
      "frequency": "~13/yr (~1.1/mo) \u2014 roughly 1 every 27 days. 4+ tier ONLY (Tier B size); 3+ tier no longer viable on 8yr.",
      "pf_base": 2.62,
      "avg_mfe_r": 2.5,
      "window": [
        "9:45-10:00"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M3 Short \u2014 Both-Swept Carve-Out (Idea)",
      "direction": "short",
      "status": "idea",
      "wr_base": "61.5%",
      "sample_size": 39,
      "action_plan": "At 10:00 ET, BOTH OR.H AND OR.L must have wicked through (loose definition: any high > OR.H AND any low < OR.L between 9:45 and 10:00). Short FVGC entry in the M3 window (10:00\u201310:15). Standard FVGC variant rules \u2014 not BOS, not protected_swing.\n\nExit Strategy: TP at OR.L touch (re-test). SL per FVGC model. 71.4% of trades reach OR.L. No BE management studied yet.",
      "notion_url": "https://www.notion.so/M3-Short-Both-Swept-Carve-Out-Idea-35ce2f0e776081f1be39d7ff086ec51e",
      "description": "Carve-out to the standard 'no shorts in M3' rule. When BOTH OR.H and OR.L have been swept (any wick beyond) by 10:00 ET, the day is in expanded-range/trending mode and short FVGCs targeting OR.L re-test work. n=39 across Oct 2023 \u2013 Mar 2026, no OOS split. Best opposite-direction M3 cell across all 4 sweep states.",
      "pre_market_conditions": "None specific. Trigger is intraday only \u2014 sweep state at 10:00 ET.",
      "tier": "B",
      "confidence": "low",
      "frequency": "~13% of days have both OR sides swept by 10:00. Conservative estimate: 2\u20133 setups/month at most.",
      "pf_base": 1.28,
      "avg_mfe_r": 5.5,
      "window": [
        "10:00-10:15"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "IFVG Reversal \u2014 v3 (anchor-to-sweep + close entry)",
      "direction": "long",
      "status": "idea",
      "wr_base": "71.0% @ 1R | 65.2% @ 1.5R | PF 2.81 (n=138 signals across 37 distinct opps \u2014 v3 re-run on TV-aligned bars)",
      "sample_size": 138,
      "action_plan": "LONG only. Killzone 9:30\u201311:00 ET. Entry TF: 3min (winner). Sweep (wick-through, wick_only strictness) of a major liquidity level. PD gate ON \u2014 entry must be below prior-day mid. Within 10 bars, a bearish 3-bar FVG forms whose NEAR EDGE (bottom) is anchored to the swept price: abs(fvg_bottom \u2212 sweep_price) \u2264 3 \u00d7 fvg_size (no proximity cap). The sweep candle itself can be bar k of the 3-bar pattern. Entry = CLOSE of the first bar (within 2 bars of FVG formation) that closes back above the FVG top. No retest. Stop = FVG bottom \u2212 5pt. Chop filter ON (skip if \u22653 bars sit inside the FVG before inversion). Obstruction filter \u22643.\n\nExit Strategy: 1.5R full close. PF 2.81 on this target (buffer=5pt on stop). WR@1R=71.0%, WR@1.5R=65.2%, avg_r=+0.630. Move stop to BE only after the first 10\u201320pt internal swing in profit \u2014 never tighter. Soft stop: full candle body close back through entry.",
      "notion_url": "https://www.notion.so/IFVG-Reversal-v3-anchor-to-sweep-close-entry-344e2f0e77608185b832c8c131a35bce",
      "description": null,
      "pre_market_conditions": "Mark: 1H swings (unswept), 4H swings (unswept), London H/L, Asia (overnight) H/L, 6am H/L, prior-day H/L/MID, NY AM rolling H/L (9:30 onward). On red-folder 8:30 news days, mark the 1-min news candle H/L if range \u226560pt. Primary confluence driver (re-run): instant_inversion=True (inversion happens within 1 bar of FVG formation, not 2) \u2014 WR 84.0% at n=50, +23.8pp lift. Secondary: large-bucket FVG sizes (bucket 6+, ~15pt+). Note: unlike the pre-fix run, swing_1H is NOT a significant confluence factor here.",
      "tier": "A",
      "confidence": "medium",
      "frequency": "~58 signals/yr (~15 distinct opps/yr)",
      "pf_base": 2.81,
      "avg_mfe_r": 2.3,
      "window": [
        "Any"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "ON Range Bias",
      "direction": "both",
      "status": "idea",
      "wr_base": "73.1% (all 4 factors, excl protected_swing)",
      "sample_size": 94,
      "action_plan": "All 4 must be TRUE: (A) ON level tested & bias confirmed \u2014 watch 30s closes through ONH/ONL, wait for price to return within 5 pts of level then re-confirm direction. (B) VIXY high (\u226525.2). (C) Gap aligns with direction. (D) 9:30 candle direction matches. Then take bos/ifvg/no_fvg only \u2014 skip protected_swing always. Prefer W1-W2 (before 10:00). W3 acceptable but lower PF.\n\nExit Strategy: 73.4% hit 1R, 59.6% hit 2R, 45.7% hit 3R. Edge decays past 3R. Recommended: BE@1R \u2192 2R (W2 optimal). W1 entries: BE@1R \u2192 2.5R (75% hit 2R, 62% hit 3R). W3: standard 1R or BE@1R \u2192 2R.",
      "notion_url": "https://www.notion.so/ON-Range-Bias-343e2f0e776081679327e2ce38aa621b",
      "description": "FVGC entries with all 4 confluence factors produce 73.1% WR and 2.41+ PF (n=94, excl protected_swing). The model is binary \u2014 all 4 factors or skip. Factors: (A) ON level tested & bias confirmed, (B) VIXY high regime, (C) gap aligns with direction, (D) 9:30 candle aligns. W2 window (9:45-10:00) peaks at 79.1% WR, 3.76 PF. ON level test establishes directional bias; FVGC signal is the entry trigger.",
      "pre_market_conditions": "Check VIXY regime: must be 'high' \u2014 if not, no play today. Note gap direction from prior close. Check overnight range for high/low levels. 5 of 4 factors are knowable pre-market: VIXY high, gap aligned, ON high/low. Factor D (930 candle) is confirmed at 9:30:30. ON breakout state machine runs 9:30-10:15.",
      "tier": "B",
      "confidence": "medium",
      "frequency": "~3/month (clusters when VIXY is high regime; ~7 trades/month on active days)",
      "pf_base": 3.76,
      "avg_mfe_r": 3.59,
      "window": [
        "9:30-9:45",
        "9:45-10:00"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "VWAP Continuation",
      "direction": "both",
      "status": "backtesting",
      "wr_base": "37.4% wins / 47.3% BE / 15.3% loss",
      "sample_size": 313,
      "action_plan": "1. Session-anchored VWAP from 9:30. 2. Wait for 3+ consecutive 30s closes above (long) or below (short) VWAP. 3. Pullback within 2pt of VWAP. 4. Entry: first 30s close back on trend side. 5. CRITICAL: measure abs(entry - VWAP). If <10 NQ pts \u2192 skip this signal. 6. R0 = abs(entry - VWAP at entry). 7. No new entries after 10:00 ET. Multiple signals/day allowed.\n\nExit Strategy: Initial SL = first 30s close on wrong side of current VWAP (dynamic). Move stop to BE when +1R reached. TP = fixed +2.5R from entry. Three outcomes: WIN +2.5R (37%), BE 0R (47%), LOSS variable avg -1.3R (15%). PF 4.61 / EV +0.73R. The BE move at +1R is non-negotiable \u2014 without it, PF collapses to ~1.1.",
      "notion_url": "https://www.notion.so/VWAP-Continuation-342e2f0e77608199821ecfbf57a1c591",
      "description": "Anchored VWAP from 9:30, 3+ trend bars, pullback within 2pt, re-cross entry in gap-aligned direction, ONLY when R0 (entry-to-VWAP distance) \u226510 NQ pts. Exit: dynamic VWAP-close SL \u2192 BE at +1R \u2192 TP at +2.5R. 8yr revalidation 2018-2026: n=313, PF 4.61 raw / 4.13 after 0.5pt slip, EV +0.73R/trade (~$217/contract). Profitable every year incl. 2025 (+$19K/ct). Original 'Calm VIXY only' filter was wrong and has been removed \u2014 high-VIXY days actually have the highest PF.",
      "pre_market_conditions": "Skip day if: (1) red folder news on calendar, (2) Wednesday, (3) prior day type = reversal_up, (4) gap <2pt. Otherwise: gap-up \u2192 longs only; gap-down \u2192 shorts only. No VIXY filter (deprecated).",
      "tier": null,
      "confidence": "high",
      "frequency": "~3/month (0.75/week) \u2014 R0\u226510pt tier",
      "pf_base": 4.61,
      "avg_mfe_r": 2.5,
      "window": [
        "9:30-9:45",
        "9:45-10:00"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "ATR Range Exhaustion Filter (High VIXY)",
      "direction": "both",
      "status": "idea",
      "wr_base": "61% at 1R (high VIXY + <30% range used + W1, n=124) | 58-61% across window variants",
      "sample_size": 124,
      "action_plan": "At FVGC entry signal: compute range_used_pct = (session_high_so_far \u2013 session_low_so_far) / rolling_40d_avg_rth_range. Only take the trade if range_used_pct < 30% (strict) or < 50% (looser). Entry must be W1 (9:30\u20139:45). Skip if >100% of expected range already used.\n\nExit Strategy: Standard FVGC exit (1R TP, SL at swing). No modification needed \u2014 the filter is pre-trade context only.",
      "notion_url": "https://www.notion.so/ATR-Range-Exhaustion-Filter-High-VIXY-342e2f0e7760816abc98f5a9af374523",
      "description": "On high VIXY days, take FVGC entries at W1 (9:30\u20139:45) when <30\u201350% of the expected daily ATR range has already been used by session open. Expected daily range = 40-day rolling average of prior rth_range. Range used = (session_high \u2013 session_low) from 9:30 to entry bar / rolling_avg_rth_range.\n\nThis is a FILTER on top of the base FVGC model, not a standalone signal. It selects the subset of W1 FVGC trades that occur early in high-volatility sessions when most of the day's expected range still remains.",
      "pre_market_conditions": "Check VIXY regime: must be 'high'. Compute expected daily range = 40-day rolling avg of prior rth_range. This is your denominator for the range_used_pct filter during the session.",
      "tier": null,
      "confidence": "low",
      "frequency": "~124 trades over dataset (high VIXY days only, W1 entries, <30% range used)",
      "pf_base": 1.65,
      "avg_mfe_r": null,
      "window": [
        "9:30-9:45"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "MACD",
      "direction": "both",
      "status": "backtesting",
      "wr_base": "61.1% (all confirmed) / 70.6\u201371.4% (best combos)",
      "sample_size": 922,
      "action_plan": "At the FVGC entry bar, switch to the 5-minute chart and check MACD(12,26,9) histogram:\n\nLONG \u2014 both required:\n\u2022 Histogram is positive (bar is above zero line)\n\u2022 Current bar histogram > previous bar histogram (expanding upward)\n\nSHORT \u2014 both required:\n\u2022 Histogram is negative (bar is below zero line)\n\u2022 Current bar histogram < previous bar histogram (expanding downward \u2014 more negative)\n\nIf either condition fails \u2192 skip the trade.\n\nBest setups (>2 PF with Strategy G runner):\n\u2022 Short + IFVG: 70.6% WR, PF 3.07 (~0.4/wk)\n\u2022 Short + Protected Swing: 65.4% WR, PF 2.42 (~0.7/wk)\n\u2022 Short + BOS: 63.4% WR, PF 2.33 (~1.1/wk)\n\u2022 Long + IFVG: 62.5% WR, PF 2.26 (~0.4/wk)\n\u2022 Long + No FVG: 63.1% WR, PF 2.14 (~1.7/wk)\n\nHistogram magnitude note: medium-sized histogram (abs value roughly 4\u20139 pts on NQ) has the highest WR at 65.6%. Very small histograms (<4 pts) = weakest confirmation at 56% WR.\n\nExit Strategy: Strategy G \u2014 Scale-Out Runner (PF 2.05, 89.3% positive months across 28-month sample):\n\u2022 At +1R: exit 33% of position, move stop to breakeven\n\u2022 At +2R: exit another 33%, move stop to +1R\n\u2022 At +3R: exit final 34%, or trail further if momentum still expanding\n\nTime guide (based on 30s-bar data, confirmed trades):\n\u2022 1R reached at median 3.5 min from entry\n\u2022 2R reached at median 10 min from entry\n\u2022 3R reached at median 18.5 min from entry\n\u2022 If 2R not reached within ~20 min, tighten trail to +0.5R\n\nAlternative for higher raw PF: Fixed 3R (PF 2.43) \u2014 but higher monthly variance.\nConservative fallback: 50% at 1R + 50% trail to 2R or +0.5R (PF 1.98, lower stress).",
      "notion_url": "https://www.notion.so/MACD-342e2f0e776081968dc8f38d9990703f",
      "description": "At the moment of FVGC entry, check the MACD(12,26,9) histogram on the 5-minute chart. Only take the trade if the histogram is expanding in the trade direction AND on the correct side of zero (strict filter). This captures real-time momentum state that static pre-market factors miss. Confirmed trades jump from 51.7% \u2192 61.1% WR and baseline PF 1.09 \u2192 2.05 with runner management. Contracting histogram trades (25% WR, PF 0.33) should be skipped entirely. Shorts outperform longs across all variants. Runner profile is strong \u2014 median 2R arrival is only 10 minutes from entry.",
      "pre_market_conditions": "None specific \u2014 this is a pure intraday entry filter. Apply on top of any existing pre-market bias. Works across all macro windows and gap directions.",
      "tier": "B",
      "confidence": "medium",
      "frequency": "~4.3 qualified setups/week (>2 PF combos); ~7.7 MACD-confirmed/week total",
      "pf_base": 2.43,
      "avg_mfe_r": 6.22,
      "window": [
        "Any"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "15m FVG Breakout Continuation",
      "direction": "both",
      "status": "backtesting",
      "wr_base": "93.3% at 1R (28W/2L), 60% at 2R, 55% at 3R",
      "sample_size": 40,
      "action_plan": "1) Price breaks through a 15m FVG \u2014 closes on the far side (non-reclaiming). 2) Within 10 bars (30s TF), an opposing-direction FVG created before the break gets inverted (close crosses its far boundary). 3) First FVGC signal in the SAME direction as the break fires within 40 bars of the inversion. Entry must be 09:30\u201310:15 NY. KEY DIFFERENCE from reversal study: trade direction matches the break direction, not opposite.\n\nExit Strategy: BE@1R \u2192 TP 3R (or hold to 5R: PF 8.33)",
      "notion_url": "https://www.notion.so/15m-FVG-Breakout-Continuation-340e2f0e776081cd922adc681ab3fdb1",
      "description": "Price breaks through an unmitigated 15-minute FVG \u2014 the gap fails to hold. An opposing FVG that was supporting the prior structure gets inverted, confirming the break is real. Then a FVGC signal fires in the breakout direction (continuation, not reversal). This is a momentum play: when 15m structure fails, the move runs hard. Median MFE 8.7R. Only works on 15m FVGs \u2014 tested all level types, nothing else comes close.",
      "pre_market_conditions": "Identify unmitigated 15-minute FVGs on the chart. These are potential breakout levels if they fail to hold.",
      "tier": "A",
      "confidence": "low",
      "frequency": "~23/yr (~1.9/mo) | ~1 every 10 days (median) | longest typical wait 38 days. NOTE: play status REJECTED \u2014 DO NOT TRADE.",
      "pf_base": 5.5,
      "avg_mfe_r": 9.44,
      "window": [
        "Any"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "M1 Short \u2014 Confluence Model",
      "direction": "short",
      "status": "verified",
      "wr_base": "68% IS / 77% OOS at 2+ conf (was: 72% at 4+)",
      "sample_size": 124,
      "action_plan": "FVGC short fires 9:30-9:45. Skip if protected_swing variant. Count 7 confluences, apply tier table for sizing. 2+ = full size runner. 4+ = max size runner.\n\nExit Strategy: Runner mode at 2+ conf. Recommended: 1/3 @ 1R + 1/3 @ 2R + 1/3 rides to 5R with NO BE on runner (+0.77R EV/trade). Never BE@1R on this play.",
      "notion_url": "https://www.notion.so/M1-Short-Confluence-Model-33de2f0e776081889879c4dcbd495996",
      "description": "Short FVGC in 9:30\u20139:45 with \u22652 of 7 pre-market + 9:30 confluences AND no hard vetoes (vixy_low, dow_monday). Confluences: gap_large_down, prior_day_weak, is_fomc_week, vixy_high, dow_friday, bear_930, c930_body_top_q. 2-tier UPGRADED to full-size runner (was light TP@1R). OOS-validated (Oct 2025-Mar 2026, n=13, 76.9% WR).",
      "pre_market_conditions": "Hard vetoes: VIXY bottom quartile OR Monday \u2192 skip. Confluences (pre-market): gap >100pts down, prior day bottom 1/3, FOMC week, VIXY top quartile, Friday. At 9:30:30: bear 930 candle + big body (top quartile, \u226523pts).",
      "tier": "A",
      "confidence": "high",
      "frequency": "Post-veto: ~50/yr (~4/mo) | every 7-11 days. 2+ confluences: ~22/yr (~1.9/mo) | every 16 days. 4+ confluences: ~6/yr | every 61 days. 9:30-FVG premium sub-tier: ~7/yr | every 55 days.",
      "pf_base": 2.44,
      "avg_mfe_r": 4,
      "window": [
        "9:30-9:45"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    },
    {
      "name": "FVGC To Opening Range H/L",
      "direction": "both",
      "status": "verified",
      "wr_base": "47%",
      "sample_size": 1001,
      "action_plan": "1. AT 9:45: mark OR.H, OR.L. If OR > 150pt \u2192 NO PLAY today. 2. From 9:45-10:15, watch 30s bars (or 1m if you find 30s too fast). 3. On each FVGC: (a) variant != ifvg, (b) direction points at unswept OR side, (c) at least one OR side still unswept \u2192 TAKE IT. 4. SIZING: 1st fire of day = 1x full size. 2nd/3rd/4th fires = 0.5x half-size. Skip 5th+ (only 0.7% of days, edge breaks down). 5. Take every qualifying fire \u2014 same-day re-entries are +EV up to trade #4. Half-sizing prevents correlated risk on multi-fire days. 6. Target = 2R, hold original SL, NEVER BE. 7. Day's done when both OR sides swept OR 10:15 ET passes.\n\nExit Strategy: Target = 2R. Hold ORIGINAL SL through any OR retest. Do NOT move to breakeven \u2014 70-85% of OR touches retrace through entry before continuing; a BE stop gets hit. Data: of trades that touch the OR target, 72-83% blow through it to 2R; only 10-16% reverse. The runner past OR is where the edge concentrates. Avg excursion beyond OR target on continuations: +6R.",
      "notion_url": "https://www.notion.so/FVGC-To-Opening-Range-H-L-33de2f0e776080409d14f582b1868b64",
      "description": "After 9:45, take 30s FVGCs pointing at an OR side that has NOT been swept yet. Target 2R, hold original SL. SIZING: 1st trade of day full 1x, 2nd-4th at 0.5x (multi-fires overlap in time and are correlated). The OR is a magnet \u2014 95% of days one side gets tested by 10:15. Kill switches: OR > 150pt | variant=ifvg | both OR sides swept | direction toward already-swept side | trade #5+ of day. 8yr validated: 30s n=1001, PF 1.78, OOS PF 1.76, drift 0.07 (very stable), +45.8R/yr. 1m alt: n=543, PF 1.93, +28R/yr (1.64x less capital accrual).",
      "pre_market_conditions": "None required. This is an intraday-only setup. OR is set at 9:45 ET.",
      "tier": "A",
      "confidence": "high",
      "frequency": "30s primary: ~119/yr (~10/mo), mean 1.49 trades/day, 34% of days have 2+ fires (~half overlap within 5min). 1m alt: ~65/yr (~5.4/mo), 18% multi-fire days. Entry window 9:45-10:15 ET.",
      "pf_base": 1.78,
      "avg_mfe_r": null,
      "window": [
        "9:45-10:00"
      ],
      "pre_met": [],
      "pre_missing": [],
      "match_status": "always"
    }
  ],
  "partial_plays": [
    {
      "name": "Thursday Inside Value Area",
      "direction": "both",
      "status": "idea",
      "wr_base": "73.7%",
      "sample_size": 76,
      "action_plan": "FVGC entry price must fall between prior day's VAL and VAH (inside the 70% value area). Long or short \u2014 both work equally (73.8% / 73.5% WR). All macro windows MW1-MW3 are valid.\n\nExit Strategy: Primary: BE@1R \u2192 2R \u2014 move stop to breakeven at +1R, hold for 2R target. 50% WR, 3.80 PF, +0.74R EV, 71% months profitable. Conservative alt: Fixed 1R (73.7% WR, +0.47R EV). Aggressive alt: BE@1R \u2192 2.5R on bearish 930 candle days (+0.86R EV).",
      "notion_url": "https://www.notion.so/Thursday-Inside-Value-Area-342e2f0e77608166bc8ed85bf46b2dca",
      "description": "On Thursdays, when the FVGC entry price falls inside the prior day's Value Area (between VAL and VAH), the model produces 73.7% WR and 2.89 PF on 76 trades. Highly significant (p=0.0002). Neither Thursday alone nor Inside VA alone is significant \u2014 the interaction is the edge. Thursdays see institutional rebalancing ahead of Friday expiration; inside the VA signals acceptance/balance, so FVGC entries catch clean rotations.",
      "pre_market_conditions": "Check calendar: is it Thursday? Night before, pull up prior day's volume profile on TradingView. Note VAH and VAL prices.",
      "tier": "B",
      "confidence": "low",
      "frequency": "~37/yr (~3.1/mo) \u2014 Thursdays only, so roughly 1 most Thursdays (sometimes multiple per Thursday). 21 months with data, only 3 losing months.",
      "pf_base": 2.89,
      "avg_mfe_r": null,
      "window": [
        "Any"
      ],
      "pre_met": [
        "thursday"
      ],
      "pre_missing": [
        "entry_inside_prior_day_value_area"
      ],
      "match_status": "partial"
    }
  ],
  "game_plan": {
    "one_liners": [
      "Thursday VP play is active. Pull up prior day's volume profile \u2014 note VAH and VAL. If FVGC entries form between VAL and VAH, take them (long or short). 73.7% WR, 2.89 PF on 76 trades (p=0.0002). MW2 (9:45-10:00) is strongest. If bearish 930 candle, consider trailing to 2R."
    ],
    "checklist": [
      "9:30 candle direction \u2014 bearish confirms most high-edge combos",
      "Watch 45-min OR width by 10:15 \u2014 WIDE = green light, TIGHT = stand down"
    ],
    "best_targets": [
      {
        "label": "London low",
        "price": 29192.25,
        "distance_pts": -2.0,
        "direction": "below"
      },
      {
        "label": "Asia low",
        "price": 29164.0,
        "distance_pts": -30.25,
        "direction": "below"
      },
      {
        "label": "1H FVG (bearish)",
        "price": 29293.75,
        "distance_pts": 99.5,
        "direction": "above"
      }
    ],
    "narrative": "Today hinges on the <b>Thursday VP play</b> signals: pull up last session\u2019s volume profile to read <b>VAH</b> and <b>VAL</b> and consider entries between them if <b>FVGC</b> entries form, with  <b>73.7% WR</b> and <b>2.89 PF</b> across <b>76 trades</b>; the strongest window is <b>MW2 9:45\u201310:00</b>, with a potential trailing to <b>2R</b> if the <b>bearish 9:30 candle</b> triggers. Verify the <b>9:30 candle direction</b> and watch the <b>45-min OR width</b> by <b>10:15</b>\u2014<b>WIDE</b> means go, <b>TIGHT</b> means stand down. Potential targets in play are near the <b>London low</b> at <b>29192.25</b> (below), the <b>Asia low</b> at <b>29164.0</b> (below), and a bearish <b>1H FVG</b> at <b>29293.75</b> (above) for a defined risk-reward setup today."
  },
  "unknown_factors": [
    {
      "factor": "gap_atr_ratio_lt_0.6",
      "plays": [
        "Small-Gap Fade Long (9:31 Entry, Gap\u226525pts)"
      ]
    },
    {
      "factor": "gap_down_ge_25pts",
      "plays": [
        "Small-Gap Fade Long (9:31 Entry, Gap\u226525pts)"
      ]
    },
    {
      "factor": "open_inside_prior_day_range",
      "plays": [
        "Small-Gap Fade Long (9:31 Entry, Gap\u226525pts)"
      ]
    }
  ]
};
