// Auto-generated by tools/week_ahead.py --export.
window.WEEK_AHEAD = {
  "schema_version": 1,
  "meta": {
    "generated_at_pt": "2026-08-30 12:00 PM PT",
    "week_start": "2026-08-31",
    "week_end": "2026-09-04",
    "gen_date": "2026-08-30"
  },
  "summary": {
    "is_fomc_week": false,
    "total_red_folder": 4,
    "has_quad_witching": false,
    "earliest_wake_pt": "5:30 am",
    "earliest_wake_day": "Friday",
    "recent_median_or45_pts": 201,
    "recent_median_f90_pts": 256,
    "recent_median_range_pts": 288,
    "recent_mean_range_pts": 339,
    "recent_max_range_pts": 748,
    "vol_spike_recent": true,
    "vol_regime": "low",
    "calendar_ok": true
  },
  "market": {
    "regime": "low",
    "regime_note": "Quiet \u2014 expect compression; dump-capture unlikely, fade extremes",
    "vol_pct": 0.22,
    "anchors": {
      "or45": 201,
      "f90": 256,
      "rest": 194,
      "full": 288
    },
    "median_range_pts": 288,
    "ref_close": 29496.2,
    "ref_date": "2026-08-28",
    "levels": [
      {
        "name": "Prior-week high",
        "price": 29811.5,
        "dist": 315.2,
        "dist_abs": 315
      },
      {
        "name": "Prior-week low",
        "price": 28946.8,
        "dist": -549.5,
        "dist_abs": 550
      },
      {
        "name": "20-day high",
        "price": 30287.5,
        "dist": 791.2,
        "dist_abs": 791
      },
      {
        "name": "20-day low",
        "price": 28313.5,
        "dist": -1182.8,
        "dist_abs": 1183
      },
      {
        "name": "All-time high",
        "price": 30968.0,
        "dist": 1471.8,
        "dist_abs": 1472
      }
    ],
    "ath_near": false,
    "ath_dist": 1471.8
  },
  "days": [
    {
      "date": "2026-08-31",
      "day_of_week": "Monday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 328,
      "hist_avg_or45_range": 186,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "live median20 \u00d7 1.00",
        "or45": {
          "point": 201,
          "lo": 151,
          "hi": 251
        },
        "f90": {
          "point": 256,
          "lo": 192,
          "hi": 320
        },
        "rest": {
          "point": 194,
          "lo": 145,
          "hi": 242
        },
        "full": {
          "point": 288,
          "lo": 216,
          "hi": 360
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Quiet regime \u2014 expect a tight OR; OR-H/L sweep + reversion plays over breakouts, M1 short on weak opens."
        },
        {
          "tag": "NOTE",
          "text": "Monday \u2014 weekend gap + range-expansion tendency; respect the opening drive direction."
        }
      ]
    },
    {
      "date": "2026-09-01",
      "day_of_week": "Tuesday",
      "events": [
        {
          "date": "2026-09-01",
          "event_type": "Other",
          "event": "ISM Manufacturing PMI",
          "time_et": "10:00",
          "impact": "High",
          "time_pt": "7:00 am",
          "time_et_fmt": "10:00 am",
          "pt_minutes": 420,
          "pre_rth": false,
          "in_window": true
        }
      ],
      "n_red_folder": 1,
      "wake_up_pt": null,
      "in_window_event": true,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 338,
      "hist_avg_or45_range": 201,
      "range_estimate": {
        "mult": 1.26,
        "event_tag": "red_folder",
        "method": "live median20 \u00d7 1.26 [red_folder]",
        "or45": {
          "point": 253,
          "lo": 190,
          "hi": 316
        },
        "f90": {
          "point": 322,
          "lo": 241,
          "hi": 402
        },
        "rest": {
          "point": 244,
          "lo": 183,
          "hi": 304
        },
        "full": {
          "point": 362,
          "lo": 272,
          "hi": 453
        }
      },
      "play_notes": [
        {
          "tag": "MID",
          "text": "10:00 am ET data lands INSIDE your window \u2014 expect a second impulse; a clean 9:30-10:00 trend can reverse on the print."
        },
        {
          "tag": "PLAY",
          "text": "Quiet regime \u2014 expect a tight OR; OR-H/L sweep + reversion plays over breakouts, M1 short on weak opens."
        }
      ]
    },
    {
      "date": "2026-09-02",
      "day_of_week": "Wednesday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 338,
      "hist_avg_or45_range": 171,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "live median20 \u00d7 1.00",
        "or45": {
          "point": 201,
          "lo": 151,
          "hi": 251
        },
        "f90": {
          "point": 256,
          "lo": 192,
          "hi": 320
        },
        "rest": {
          "point": 194,
          "lo": 145,
          "hi": 242
        },
        "full": {
          "point": 288,
          "lo": 216,
          "hi": 360
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Quiet regime \u2014 expect a tight OR; OR-H/L sweep + reversion plays over breakouts, M1 short on weak opens."
        }
      ]
    },
    {
      "date": "2026-09-03",
      "day_of_week": "Thursday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 366,
      "hist_avg_or45_range": 212,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "live median20 \u00d7 1.00",
        "or45": {
          "point": 201,
          "lo": 151,
          "hi": 251
        },
        "f90": {
          "point": 256,
          "lo": 192,
          "hi": 320
        },
        "rest": {
          "point": 194,
          "lo": 145,
          "hi": 242
        },
        "full": {
          "point": 288,
          "lo": 216,
          "hi": 360
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Quiet regime \u2014 expect a tight OR; OR-H/L sweep + reversion plays over breakouts, M1 short on weak opens."
        }
      ]
    },
    {
      "date": "2026-09-04",
      "day_of_week": "Friday",
      "events": [
        {
          "date": "2026-09-04",
          "event_type": "Other",
          "event": "Average Hourly Earnings m/m",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-09-04",
          "event_type": "NFP",
          "event": "Non-Farm Employment Change",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-09-04",
          "event_type": "Other",
          "event": "Unemployment Rate",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        }
      ],
      "n_red_folder": 3,
      "wake_up_pt": "5:30 am",
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 349,
      "hist_avg_or45_range": 203,
      "range_estimate": {
        "mult": 1.3,
        "event_tag": "NFP",
        "method": "live median20 \u00d7 1.30 [NFP]",
        "or45": {
          "point": 262,
          "lo": 196,
          "hi": 327
        },
        "f90": {
          "point": 333,
          "lo": 249,
          "hi": 416
        },
        "rest": {
          "point": 252,
          "lo": 189,
          "hi": 315
        },
        "full": {
          "point": 375,
          "lo": 281,
          "hi": 469
        }
      },
      "play_notes": [
        {
          "tag": "ARMED",
          "text": "Pre-RTH market-mover \u2014 dump-capture watch (WR scales with dump size) + opening-FVG short tier-2 more likely. Wait for the 9:30 reaction, don't pre-position."
        }
      ]
    }
  ],
  "baselines": {
    "event_multipliers": {
      "quiet": {
        "mult": 0.97,
        "n": 1925
      },
      "red_folder": {
        "mult": 1.26,
        "n": 237
      },
      "NFP": {
        "mult": 1.3,
        "n": 59
      },
      "fomc": {
        "mult": 1.24,
        "n": 210
      }
    },
    "base_avg_range": 214
  },
  "notes": [
    "Times shown in PST/PDT (America/Los_Angeles). 8:30 AM ET = 5:30 AM PST.",
    "Range estimates are split by window \u2014 first 45 min (your opening range), first 90 min, and the rest (11:00-close) \u2014 each the recent-median range for that window scaled by the event multiplier.",
    "These are event-conditioned BASELINES, not the same-morning OR-width forecast (which needs that day's gap + overnight range)."
  ]
};
