// Auto-generated by tools/week_ahead.py --export.
window.WEEK_AHEAD = {
  "schema_version": 1,
  "meta": {
    "generated_at_pt": "2026-07-15 06:13 AM PT",
    "week_start": "2026-07-13",
    "week_end": "2026-07-17",
    "gen_date": "2026-07-15"
  },
  "summary": {
    "is_fomc_week": false,
    "total_red_folder": 8,
    "has_quad_witching": false,
    "earliest_wake_pt": "5:30 am",
    "earliest_wake_day": "Tuesday",
    "recent_median_or45_pts": null,
    "recent_median_f90_pts": null,
    "recent_median_range_pts": null,
    "recent_mean_range_pts": null,
    "recent_max_range_pts": null,
    "vol_spike_recent": false,
    "vol_regime": null,
    "calendar_ok": true
  },
  "market": null,
  "days": [
    {
      "date": "2026-07-13",
      "day_of_week": "Monday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 328,
      "hist_avg_or45_range": 186,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "weekday avg (no live) \u00d7 1.00",
        "or45": {
          "point": 186,
          "lo": 139,
          "hi": 232
        },
        "f90": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "rest": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "full": {
          "point": 328,
          "lo": 246,
          "hi": 409
        }
      },
      "play_notes": [
        {
          "tag": "NOTE",
          "text": "Monday \u2014 weekend gap + range-expansion tendency; respect the opening drive direction."
        }
      ]
    },
    {
      "date": "2026-07-14",
      "day_of_week": "Tuesday",
      "events": [
        {
          "date": "2026-07-14",
          "event_type": "CPI",
          "event": "Core CPI m/m",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-07-14",
          "event_type": "CPI",
          "event": "Core CPI y/y",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-07-14",
          "event_type": "CPI",
          "event": "CPI m/m",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-07-14",
          "event_type": "CPI",
          "event": "CPI y/y",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-07-14",
          "event_type": "Other",
          "event": "Fed Chairman Warsh Testifies",
          "time_et": "10:00",
          "impact": "High",
          "time_pt": "7:00 am",
          "time_et_fmt": "10:00 am",
          "pt_minutes": 420,
          "pre_rth": false,
          "in_window": true
        }
      ],
      "n_red_folder": 5,
      "wake_up_pt": "5:30 am",
      "in_window_event": true,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 338,
      "hist_avg_or45_range": 201,
      "range_estimate": {
        "mult": 1.26,
        "event_tag": "CPI",
        "method": "weekday avg (no live) \u00d7 1.26 [CPI]",
        "or45": {
          "point": 253,
          "lo": 189,
          "hi": 316
        },
        "f90": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "rest": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "full": {
          "point": 426,
          "lo": 319,
          "hi": 532
        }
      },
      "play_notes": [
        {
          "tag": "ARMED",
          "text": "Pre-RTH market-mover \u2014 dump-capture watch (WR scales with dump size) + opening-FVG short tier-2 more likely. Wait for the 9:30 reaction, don't pre-position."
        },
        {
          "tag": "MID",
          "text": "10:00 am ET data lands INSIDE your window \u2014 expect a second impulse; a clean 9:30-10:00 trend can reverse on the print."
        }
      ]
    },
    {
      "date": "2026-07-15",
      "day_of_week": "Wednesday",
      "events": [
        {
          "date": "2026-07-15",
          "event_type": "PPI",
          "event": "Core PPI m/m",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-07-15",
          "event_type": "PPI",
          "event": "PPI m/m",
          "time_et": "08:30",
          "impact": "High",
          "time_pt": "5:30 am",
          "time_et_fmt": "8:30 am",
          "pt_minutes": 330,
          "pre_rth": true,
          "in_window": false
        },
        {
          "date": "2026-07-15",
          "event_type": "Other",
          "event": "Fed Chairman Warsh Testifies",
          "time_et": "10:00",
          "impact": "High",
          "time_pt": "7:00 am",
          "time_et_fmt": "10:00 am",
          "pt_minutes": 420,
          "pre_rth": false,
          "in_window": true
        }
      ],
      "n_red_folder": 3,
      "wake_up_pt": "5:30 am",
      "in_window_event": true,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 338,
      "hist_avg_or45_range": 171,
      "range_estimate": {
        "mult": 1.26,
        "event_tag": "PPI",
        "method": "weekday avg (no live) \u00d7 1.26 [PPI]",
        "or45": {
          "point": 215,
          "lo": 162,
          "hi": 269
        },
        "f90": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "rest": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "full": {
          "point": 425,
          "lo": 319,
          "hi": 531
        }
      },
      "play_notes": [
        {
          "tag": "ARMED",
          "text": "Pre-RTH market-mover \u2014 dump-capture watch (WR scales with dump size) + opening-FVG short tier-2 more likely. Wait for the 9:30 reaction, don't pre-position."
        },
        {
          "tag": "MID",
          "text": "10:00 am ET data lands INSIDE your window \u2014 expect a second impulse; a clean 9:30-10:00 trend can reverse on the print."
        }
      ]
    },
    {
      "date": "2026-07-16",
      "day_of_week": "Thursday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 366,
      "hist_avg_or45_range": 212,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "weekday avg (no live) \u00d7 1.00",
        "or45": {
          "point": 212,
          "lo": 159,
          "hi": 265
        },
        "f90": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "rest": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "full": {
          "point": 366,
          "lo": 275,
          "hi": 458
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Standard matrix \u2014 M1 short / OR-H/L / opening-FVG geometry on a clean open."
        }
      ]
    },
    {
      "date": "2026-07-17",
      "day_of_week": "Friday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 349,
      "hist_avg_or45_range": 203,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "weekday avg (no live) \u00d7 1.00",
        "or45": {
          "point": 203,
          "lo": 152,
          "hi": 253
        },
        "f90": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "rest": {
          "point": null,
          "lo": null,
          "hi": null
        },
        "full": {
          "point": 349,
          "lo": 262,
          "hi": 436
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Standard matrix \u2014 M1 short / OR-H/L / opening-FVG geometry on a clean open."
        }
      ]
    }
  ],
  "baselines": {
    "event_multipliers": {
      "quiet": {
        "mult": 0.97,
        "n": 1925
      },
      "red_folder": {
        "mult": 1.26,
        "n": 237
      },
      "NFP": {
        "mult": 1.3,
        "n": 59
      },
      "fomc": {
        "mult": 1.24,
        "n": 210
      }
    },
    "base_avg_range": 214
  },
  "notes": [
    "Times shown in PST/PDT (America/Los_Angeles). 8:30 AM ET = 5:30 AM PST.",
    "Range estimates are split by window \u2014 first 45 min (your opening range), first 90 min, and the rest (11:00-close) \u2014 each the recent-median range for that window scaled by the event multiplier.",
    "These are event-conditioned BASELINES, not the same-morning OR-width forecast (which needs that day's gap + overnight range)."
  ]
};
