// Auto-generated by tools/week_ahead.py --export.
window.WEEK_AHEAD = {
  "schema_version": 1,
  "meta": {
    "generated_at_pt": "2026-07-05 12:01 PM PT",
    "week_start": "2026-07-06",
    "week_end": "2026-07-10",
    "gen_date": "2026-07-05"
  },
  "summary": {
    "is_fomc_week": false,
    "total_red_folder": 2,
    "has_quad_witching": false,
    "earliest_wake_pt": null,
    "earliest_wake_day": null,
    "recent_median_or45_pts": 314,
    "recent_median_f90_pts": 412,
    "recent_median_range_pts": 577,
    "recent_mean_range_pts": 671,
    "recent_max_range_pts": 1620,
    "vol_spike_recent": true,
    "vol_regime": "elevated",
    "calendar_ok": true
  },
  "market": {
    "regime": "elevated",
    "regime_note": "Elevated vol \u2014 dump-capture armed, wider stops, size up on A+",
    "vol_pct": 0.8,
    "anchors": {
      "or45": 314,
      "f90": 412,
      "rest": 388,
      "full": 577
    },
    "median_range_pts": 577,
    "ref_close": 29539.5,
    "ref_date": "2026-07-02",
    "levels": [
      {
        "name": "Prior-week low",
        "price": 29273.8,
        "dist": -265.8,
        "dist_abs": 266
      },
      {
        "name": "Prior-week high",
        "price": 30599.8,
        "dist": 1060.2,
        "dist_abs": 1060
      },
      {
        "name": "20-day low",
        "price": 28227.8,
        "dist": -1311.8,
        "dist_abs": 1312
      },
      {
        "name": "Recent high (60d)",
        "price": 30968.0,
        "dist": 1428.5,
        "dist_abs": 1428
      }
    ],
    "ath_near": false,
    "ath_dist": 1428.5
  },
  "days": [
    {
      "date": "2026-07-06",
      "day_of_week": "Monday",
      "events": [
        {
          "date": "2026-07-06",
          "event_type": "Other",
          "event": "ISM Services PMI",
          "time_et": "10:00",
          "impact": "High",
          "time_pt": "7:00 am",
          "time_et_fmt": "10:00 am",
          "pt_minutes": 420,
          "pre_rth": false,
          "in_window": true
        }
      ],
      "n_red_folder": 1,
      "wake_up_pt": null,
      "in_window_event": true,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 328,
      "hist_avg_or45_range": 186,
      "range_estimate": {
        "mult": 1.26,
        "event_tag": "red_folder",
        "method": "live median20 \u00d7 1.26 [red_folder]",
        "or45": {
          "point": 395,
          "lo": 296,
          "hi": 494
        },
        "f90": {
          "point": 518,
          "lo": 388,
          "hi": 647
        },
        "rest": {
          "point": 488,
          "lo": 366,
          "hi": 610
        },
        "full": {
          "point": 725,
          "lo": 544,
          "hi": 906
        }
      },
      "play_notes": [
        {
          "tag": "MID",
          "text": "10:00 am ET data lands INSIDE your window \u2014 expect a second impulse; a clean 9:30-10:00 trend can reverse on the print."
        },
        {
          "tag": "PLAY",
          "text": "Vol elevated \u2014 dump-capture armed, wider OR expected; favor momentum continuation over fades."
        },
        {
          "tag": "NOTE",
          "text": "Monday \u2014 weekend gap + range-expansion tendency; respect the opening drive direction."
        }
      ]
    },
    {
      "date": "2026-07-07",
      "day_of_week": "Tuesday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 338,
      "hist_avg_or45_range": 201,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "live median20 \u00d7 1.00",
        "or45": {
          "point": 314,
          "lo": 236,
          "hi": 393
        },
        "f90": {
          "point": 412,
          "lo": 309,
          "hi": 515
        },
        "rest": {
          "point": 388,
          "lo": 291,
          "hi": 485
        },
        "full": {
          "point": 577,
          "lo": 433,
          "hi": 721
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Vol elevated \u2014 dump-capture armed, wider OR expected; favor momentum continuation over fades."
        }
      ]
    },
    {
      "date": "2026-07-08",
      "day_of_week": "Wednesday",
      "events": [
        {
          "date": "2026-07-08",
          "event_type": "FOMC Meeting Minutes",
          "event": "FOMC Meeting Minutes",
          "time_et": "14:00",
          "impact": "High",
          "time_pt": "11:00 am",
          "time_et_fmt": "2:00 pm",
          "pt_minutes": 660,
          "pre_rth": false,
          "in_window": false
        }
      ],
      "n_red_folder": 1,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 338,
      "hist_avg_or45_range": 171,
      "range_estimate": {
        "mult": 1.26,
        "event_tag": "FOMC",
        "method": "live median20 \u00d7 1.26 [FOMC]",
        "or45": {
          "point": 395,
          "lo": 296,
          "hi": 494
        },
        "f90": {
          "point": 518,
          "lo": 388,
          "hi": 647
        },
        "rest": {
          "point": 488,
          "lo": 366,
          "hi": 610
        },
        "full": {
          "point": 725,
          "lo": 544,
          "hi": 906
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Vol elevated \u2014 dump-capture armed, wider OR expected; favor momentum continuation over fades."
        }
      ]
    },
    {
      "date": "2026-07-09",
      "day_of_week": "Thursday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 366,
      "hist_avg_or45_range": 212,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "live median20 \u00d7 1.00",
        "or45": {
          "point": 314,
          "lo": 236,
          "hi": 393
        },
        "f90": {
          "point": 412,
          "lo": 309,
          "hi": 515
        },
        "rest": {
          "point": 388,
          "lo": 291,
          "hi": 485
        },
        "full": {
          "point": 577,
          "lo": 433,
          "hi": 721
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Vol elevated \u2014 dump-capture armed, wider OR expected; favor momentum continuation over fades."
        }
      ]
    },
    {
      "date": "2026-07-10",
      "day_of_week": "Friday",
      "events": [],
      "n_red_folder": 0,
      "wake_up_pt": null,
      "in_window_event": false,
      "quad_witching": false,
      "fomc_decision": false,
      "hist_avg_rth_range": 349,
      "hist_avg_or45_range": 203,
      "range_estimate": {
        "mult": 1.0,
        "event_tag": null,
        "method": "live median20 \u00d7 1.00",
        "or45": {
          "point": 314,
          "lo": 236,
          "hi": 393
        },
        "f90": {
          "point": 412,
          "lo": 309,
          "hi": 515
        },
        "rest": {
          "point": 388,
          "lo": 291,
          "hi": 485
        },
        "full": {
          "point": 577,
          "lo": 433,
          "hi": 721
        }
      },
      "play_notes": [
        {
          "tag": "PLAY",
          "text": "Vol elevated \u2014 dump-capture armed, wider OR expected; favor momentum continuation over fades."
        }
      ]
    }
  ],
  "baselines": {
    "event_multipliers": {
      "quiet": {
        "mult": 0.97,
        "n": 1925
      },
      "red_folder": {
        "mult": 1.26,
        "n": 237
      },
      "NFP": {
        "mult": 1.3,
        "n": 59
      },
      "fomc": {
        "mult": 1.24,
        "n": 210
      }
    },
    "base_avg_range": 214
  },
  "notes": [
    "Times shown in PST/PDT (America/Los_Angeles). 8:30 AM ET = 5:30 AM PST.",
    "Range estimates are split by window \u2014 first 45 min (your opening range), first 90 min, and the rest (11:00-close) \u2014 each the recent-median range for that window scaled by the event multiplier.",
    "These are event-conditioned BASELINES, not the same-morning OR-width forecast (which needs that day's gap + overnight range)."
  ]
};
